In [1]:
%matplotlib widget
from bmcs_shear.matmod.sz_concrete.sz_advanced import ConcreteMaterialModelAdv
import numpy as np
# w = np.linspace(0,1,100)
# print(ConcreteMaterialModel.get_sigma_w(w))

In [2]:
ccm = ConcreteMaterialModelAdv()

In [3]:
ConcreteMaterialModelAdv().interact()

<lambdifygenerated-5>:2: RuntimeWarning: invalid value encountered in sqrt
  return (select([less_equal(w, 0),True], [0,0.25*f_c*s*(-sqrt(2)*sqrt(w/d_a) + 1)*((2.44 - 39.04/f_c)*abs(s/w)**3 + 9.8/f_c)/(w*(s**4*(2.44 - 39.04/f_c)/w**4 + 1))], default=nan))


In [7]:
w = np.linspace(-1,1, 100)
s = np.linspace(-1,1, 100)
ccm.get_sigma_ag(w,s)

array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
       -0.26110021, -0.44189315, -0.56128585, -0.65527825, -0.73434434,
       -0.80327984, -0.86475731, -0.9204472 , -0.97147626, -1.01864711,
       -1.06255545, -1.10365787, -1.14231343, -1.17881058, -1.21338522,
       -1.24623314, -1.27751901, -1.30738288, -1.33594504, -1.36

In [4]:
ccm.get_w_tc()

0.23793425945734095

In [5]:
import sympy as sp
w = sp.Symbol('w')

sp.sign(w)

sign(w)

In [6]:
get_sign = sp.lambdify(w, sp.sign(w))
get_sign

<function _lambdifygenerated(w)>

In [7]:
import numpy as np
w_ = np.linspace(-4,0, 100)
s_ = np.linspace(-2,2, 10)
#w_a =  2 - 1/2 * (get_sign(w_ )) * w_ #* w_  #* w_ 1/2 *   1 - 1/2 * + 1
#w_a = get_sign(w_ - 1/2) * (w_)
#w_a =
w_1 = get_sign(w_ + 1/34) * (w_ + 1e-9)#+ 1e-9) #+ 1/34
w_1, w_

(array([4.00000000e+00, 3.95959596e+00, 3.91919192e+00, 3.87878788e+00,
        3.83838384e+00, 3.79797980e+00, 3.75757576e+00, 3.71717172e+00,
        3.67676768e+00, 3.63636364e+00, 3.59595959e+00, 3.55555555e+00,
        3.51515151e+00, 3.47474747e+00, 3.43434343e+00, 3.39393939e+00,
        3.35353535e+00, 3.31313131e+00, 3.27272727e+00, 3.23232323e+00,
        3.19191919e+00, 3.15151515e+00, 3.11111111e+00, 3.07070707e+00,
        3.03030303e+00, 2.98989899e+00, 2.94949495e+00, 2.90909091e+00,
        2.86868687e+00, 2.82828283e+00, 2.78787879e+00, 2.74747475e+00,
        2.70707071e+00, 2.66666667e+00, 2.62626263e+00, 2.58585858e+00,
        2.54545454e+00, 2.50505050e+00, 2.46464646e+00, 2.42424242e+00,
        2.38383838e+00, 2.34343434e+00, 2.30303030e+00, 2.26262626e+00,
        2.22222222e+00, 2.18181818e+00, 2.14141414e+00, 2.10101010e+00,
        2.06060606e+00, 2.02020202e+00, 1.97979798e+00, 1.93939394e+00,
        1.89898990e+00, 1.85858586e+00, 1.81818182e+00, 1.777777

In [8]:
s_, w_1 = np.meshgrid(s_, w_1)

In [9]:
#ccm.get_sig_a(w_, s_)
sig_a, tau_a = ccm.get_sig_a(w_1, s_)

TypeError: get_sig_a() takes 2 positional arguments but 3 were given

In [ ]:
tau_a

In [ ]:
import matplotlib.pyplot as plt
plt.subplots(1, 1)
ax_s = plt.axes(projection='3d')
ax_s.plot_surface(w_1, s_, tau_a, cmap='viridis', edgecolor='none')
ax_s.set_xlabel(r'$w\;\;\mathrm{[mm]}$')
ax_s.set_ylabel(r'$s\;\;\mathrm{[mm]}$')
ax_s.set_zlabel(r'$\tau\;\;\mathrm{[MPa]}$')

In [ ]:
import sympy as sp
import numpy as np
import matplotlib.pylab as plt
sp.init_printing()

In [10]:
w = sp.Symbol(r'w', real=True)
s = sp.Symbol(r's', real = True)
d_a, E_c = sp.symbols(r'd_a, E_c', nonnegative=True)
f_t = sp.symbols(r'f_t', nonnegative=True)
c_2 = sp.Symbol('c_2', nonnegative=True)
c_1 = sp.Symbol('c_1', nonnegative=True)
f_c = sp.Symbol('f_c', nonnegative =True)
#G_f, L_c = sp.symbols('G_f, L_c', nonnegative = True)

In [11]:
G_f = 0.028 * f_c ** 0.18 * d_a ** 0.32

L_c = E_c * G_f / f_t ** 2

w_cr = f_t / E_c * L_c

eps_cp = w_cr / L_c

eps_p = w / L_c

f_co = 2 * f_t

w_tc = 5.14 * G_f / f_t

In [12]:
sig_w = sp.Piecewise(
        (- f_c, w < - w_cr),
        (-(f_co + (f_c - f_co) * sp.sqrt(1 - ((eps_cp - eps_p) / (eps_cp)) ** 2)), - w_cr < w ),
        (- 2 * f_t, w == 0),
        (E_c * eps_p, E_c * w / L_c <= f_t),
        (f_t * (1 + ((c_1 * w)/(w_tc))**3) * sp.exp((-c_2* w)/(w_tc)) - (w/w_tc) * \
        (1 + c_1**3) * sp.exp(-c_2), w > w_cr)
    )

In [13]:
sig_w

Piecewise((-f_c, w < -0.028*d_a**0.32*f_c**0.18/f_t), (-2*f_t - 35.7142857142857*(f_c - 2*f_t)*sqrt(-E_c**2*(-d_a**(-0.32)*f_c**(-0.18)*f_t**2*w/E_c + 0.028*f_t/E_c)**2/f_t**2 + 0.000784), w > -0.028*d_a**0.32*f_c**0.18/f_t), (35.7142857142857*d_a**(-0.32)*f_c**(-0.18)*f_t**2*w, f_t >= 35.7142857142857*d_a**(-0.32)*f_c**(-0.18)*f_t**2*w), (-6.94830461367426*d_a**(-0.32)*f_c**(-0.18)*f_t*w*(c_1**3 + 1)*exp(-c_2) + f_t*(335.456760731011*c_1**3*d_a**(-0.96)*f_c**(-0.54)*f_t**3*w**3 + 1)*exp(-6.94830461367426*c_2*d_a**(-0.32)*f_c**(-0.18)*f_t*w), w > 0.028*d_a**0.32*f_c**0.18/f_t))

In [14]:
params = {
    d_a : 22,
    E_c : 28000,
    f_t : 3,
    c_2 : 6,
    c_1 : 3,
    f_c : 30
}

In [15]:
get_sig_w = sp.lambdify((w), sig_w.subs(params), 'numpy')
sig_w.subs(params)

Piecewise((-30, w < -0.0462907119566811), (-518.462537851205*sqrt(0.00214283001345642 - (0.0462907119566811 - w)**2) - 6, w > -0.0462907119566811), (64.8078172314006*w, 64.8078172314006*w <= 3), (-117.679564363114*w*exp(-6) + 3*(2004.43891704877*w**3 + 1)*exp(-25.2170495063816*w), w > 0.0462907119566811))

In [16]:
_, (ax1) = plt.subplots(1, 1, figsize=(10,5))
w_ = np.linspace(-1,1, 100)
sig = get_sig_w(w_)
ax1.plot(w_, sig, color='blue', lw=2);

NameError: name 'plt' is not defined

In [17]:
print(sig)

NameError: name 'sig' is not defined

In [18]:
f_ce = f_c * (1 / (0.8))
sig_w = sp.Piecewise(
        (- f_c, E_c * w / L_c < - f_c),
        (- f_ce * (2 * (eps_p / -0.002) - (eps_p / -0.002) ** 2), w <= w_cr),
        (f_t * (1 + ((c_1 * w)/(w_tc))**3) * sp.exp((-c_2* w)/(w_tc)) - (w/w_tc) * \
        (1 + c_1**3) * sp.exp(-c_2), w > w_cr)
    )
sig_w

Piecewise((-f_c, f_c < -35.7142857142857*d_a**(-0.32)*f_c**(-0.18)*f_t**2*w), (-1.25*f_c*(-35714.2857142857*d_a**(-0.32)*f_c**(-0.18)*f_t**2*w/E_c - 318877551.020408*d_a**(-0.64)*f_c**(-0.36)*f_t**4*w**2/E_c**2), w <= 0.028*d_a**0.32*f_c**0.18/f_t), (-6.94830461367426*d_a**(-0.32)*f_c**(-0.18)*f_t*w*(c_1**3 + 1)*exp(-c_2) + f_t*(335.456760731011*c_1**3*d_a**(-0.96)*f_c**(-0.54)*f_t**3*w**3 + 1)*exp(-6.94830461367426*c_2*d_a**(-0.32)*f_c**(-0.18)*f_t*w), True))

In [19]:
get_sig_w = sp.lambdify((w), sig_w.subs(params), 'numpy')
sig_w.subs(params)

Piecewise((-30, 64.8078172314006*w < -30), (50.2238501390939*w**2 + 86.7961837920544*w, w <= 0.0462907119566811), (-117.679564363114*w*exp(-6) + 3*(2004.43891704877*w**3 + 1)*exp(-25.2170495063816*w), True))

In [20]:
_, (ax1) = plt.subplots(1, 1, figsize=(10,5))
w_ = np.linspace(-1,1, 100)
sig = get_sig_w(w_)
ax1.plot(w_, sig, color='blue', lw=2);

NameError: name 'plt' is not defined

In [21]:
sig

NameError: name 'sig' is not defined

In [22]:
w_

array([-4.        , -3.95959596, -3.91919192, -3.87878788, -3.83838384,
       -3.7979798 , -3.75757576, -3.71717172, -3.67676768, -3.63636364,
       -3.5959596 , -3.55555556, -3.51515152, -3.47474747, -3.43434343,
       -3.39393939, -3.35353535, -3.31313131, -3.27272727, -3.23232323,
       -3.19191919, -3.15151515, -3.11111111, -3.07070707, -3.03030303,
       -2.98989899, -2.94949495, -2.90909091, -2.86868687, -2.82828283,
       -2.78787879, -2.74747475, -2.70707071, -2.66666667, -2.62626263,
       -2.58585859, -2.54545455, -2.50505051, -2.46464646, -2.42424242,
       -2.38383838, -2.34343434, -2.3030303 , -2.26262626, -2.22222222,
       -2.18181818, -2.14141414, -2.1010101 , -2.06060606, -2.02020202,
       -1.97979798, -1.93939394, -1.8989899 , -1.85858586, -1.81818182,
       -1.77777778, -1.73737374, -1.6969697 , -1.65656566, -1.61616162,
       -1.57575758, -1.53535354, -1.49494949, -1.45454545, -1.41414141,
       -1.37373737, -1.33333333, -1.29292929, -1.25252525, -1.21

In [23]:
r = s / w

tau_0 = 0.25 * f_c

a_3 = 2.45 / tau_0

a_4 = 2.44 * (1 - (4 / tau_0))
tau_s = tau_0 * (1 - sp.sqrt((2 * w) / d_a)) * r * (a_3 + (a_4 * sp.Abs(r) ** 3)) / (1 + (a_4 * r ** 4))
tau_s

0.25*f_c*s*(-sqrt(2)*sqrt(w/d_a) + 1)*((2.44 - 39.04/f_c)*Abs(s/w)**3 + 9.8/f_c)/(w*(s**4*(2.44 - 39.04/f_c)/w**4 + 1))

In [24]:
get_tau_s = sp.lambdify((w,s), tau_s.subs(params), 'numpy')
tau_s.subs(params)

7.5*s*(-sqrt(11)*sqrt(w)/11 + 1)*(1.13866666666667*Abs(s/w)**3 + 0.326666666666667)/(w*(1.13866666666667*s**4/w**4 + 1))

In [25]:
_, (ax1) = plt.subplots(1, 1, figsize=(10,5))
w_ = np.linspace(0,1, 100)
s_ = np.linspace(-1,1, 100)
tau = get_tau_s(w_, s_)
ax1.plot(s_, tau, color='blue', lw=2);

NameError: name 'plt' is not defined

In [26]:
w = sp.Symbol(r'w', real=True)
s = sp.Symbol(r's', real = True)
d_a, E_c = sp.symbols(r'd_a, E_c', nonnegative=True)
f_t = sp.symbols(r'f_t', nonnegative=True)
c_2 = sp.Symbol('c_2', nonnegative=True)
c_1 = sp.Symbol('c_1', nonnegative=True)
f_c = sp.Symbol('f_c', nonnegative =True)
#G_f, L_c = sp.symbols('G_f, L_c', nonnegative = True)

In [27]:
G_f = 0.028 * f_c ** 0.18 * d_a ** 0.32

L_c = E_c * G_f / f_t ** 2

w_cr = f_t / E_c * L_c

eps_cp = w_cr / L_c

eps_p = w / L_c

f_co = 2 * f_t

w_tc = 5.14 * G_f / f_t

In [28]:
sig_w = sp.Piecewise(
        (- f_c, w < - w_cr),
        (-(f_co + (f_c - f_co) * sp.sqrt(1 - ((eps_cp - eps_p) / (eps_cp)) ** 2)), - w_cr < w ),
        (- 2 * f_t, w == 0),
        (E_c * eps_p, E_c * w / L_c <= f_t),
        (f_t * (1 + ((c_1 * w)/(w_tc))**3) * sp.exp((-c_2* w)/(w_tc)) - (w/w_tc) * \
        (1 + c_1**3) * sp.exp(-c_2), w > w_cr)
    )

In [29]:
sig_w

Piecewise((-f_c, w < -0.028*d_a**0.32*f_c**0.18/f_t), (-2*f_t - 35.7142857142857*(f_c - 2*f_t)*sqrt(-E_c**2*(-d_a**(-0.32)*f_c**(-0.18)*f_t**2*w/E_c + 0.028*f_t/E_c)**2/f_t**2 + 0.000784), w > -0.028*d_a**0.32*f_c**0.18/f_t), (35.7142857142857*d_a**(-0.32)*f_c**(-0.18)*f_t**2*w, f_t >= 35.7142857142857*d_a**(-0.32)*f_c**(-0.18)*f_t**2*w), (-6.94830461367426*d_a**(-0.32)*f_c**(-0.18)*f_t*w*(c_1**3 + 1)*exp(-c_2) + f_t*(335.456760731011*c_1**3*d_a**(-0.96)*f_c**(-0.54)*f_t**3*w**3 + 1)*exp(-6.94830461367426*c_2*d_a**(-0.32)*f_c**(-0.18)*f_t*w), w > 0.028*d_a**0.32*f_c**0.18/f_t))

In [30]:
params = {
    d_a : 22,
    E_c : 28000,
    f_t : 3,
    c_2 : 6,
    c_1 : 3,
    f_c : 30
}

In [31]:
get_sig_w = sp.lambdify((w), sig_w.subs(params), 'numpy')
sig_w.subs(params)

Piecewise((-30, w < -0.0462907119566811), (-518.462537851205*sqrt(0.00214283001345642 - (0.0462907119566811 - w)**2) - 6, w > -0.0462907119566811), (64.8078172314006*w, 64.8078172314006*w <= 3), (-117.679564363114*w*exp(-6) + 3*(2004.43891704877*w**3 + 1)*exp(-25.2170495063816*w), w > 0.0462907119566811))

In [32]:
_, (ax1) = plt.subplots(1, 1, figsize=(10,5))
w_ = np.linspace(-1,1, 100)
sig = get_sig_w(w_)
ax1.plot(w_, sig, color='blue', lw=2);

NameError: name 'plt' is not defined

In [33]:
print(sig)

NameError: name 'sig' is not defined

In [34]:
f_ce = f_c * (1 / (0.8))
sig_w = sp.Piecewise(
        (- f_c, E_c * w / L_c < - f_c),
        (- f_ce * (2 * (eps_p / -0.002) - (eps_p / -0.002) ** 2), w <= w_cr),
        (f_t * (1 + ((c_1 * w)/(w_tc))**3) * sp.exp((-c_2* w)/(w_tc)) - (w/w_tc) * \
        (1 + c_1**3) * sp.exp(-c_2), w > w_cr)
    )
sig_w

Piecewise((-f_c, f_c < -35.7142857142857*d_a**(-0.32)*f_c**(-0.18)*f_t**2*w), (-1.25*f_c*(-35714.2857142857*d_a**(-0.32)*f_c**(-0.18)*f_t**2*w/E_c - 318877551.020408*d_a**(-0.64)*f_c**(-0.36)*f_t**4*w**2/E_c**2), w <= 0.028*d_a**0.32*f_c**0.18/f_t), (-6.94830461367426*d_a**(-0.32)*f_c**(-0.18)*f_t*w*(c_1**3 + 1)*exp(-c_2) + f_t*(335.456760731011*c_1**3*d_a**(-0.96)*f_c**(-0.54)*f_t**3*w**3 + 1)*exp(-6.94830461367426*c_2*d_a**(-0.32)*f_c**(-0.18)*f_t*w), True))

In [35]:
get_sig_w = sp.lambdify((w), sig_w.subs(params), 'numpy')
sig_w.subs(params)

Piecewise((-30, 64.8078172314006*w < -30), (50.2238501390939*w**2 + 86.7961837920544*w, w <= 0.0462907119566811), (-117.679564363114*w*exp(-6) + 3*(2004.43891704877*w**3 + 1)*exp(-25.2170495063816*w), True))

In [36]:
_, (ax1) = plt.subplots(1, 1, figsize=(10,5))
w_ = np.linspace(-1,1, 100)
sig = get_sig_w(w_)
ax1.plot(w_, sig, color='blue', lw=2);

NameError: name 'plt' is not defined

In [37]:
sig

NameError: name 'sig' is not defined

In [38]:
w_

array([-4.        , -3.95959596, -3.91919192, -3.87878788, -3.83838384,
       -3.7979798 , -3.75757576, -3.71717172, -3.67676768, -3.63636364,
       -3.5959596 , -3.55555556, -3.51515152, -3.47474747, -3.43434343,
       -3.39393939, -3.35353535, -3.31313131, -3.27272727, -3.23232323,
       -3.19191919, -3.15151515, -3.11111111, -3.07070707, -3.03030303,
       -2.98989899, -2.94949495, -2.90909091, -2.86868687, -2.82828283,
       -2.78787879, -2.74747475, -2.70707071, -2.66666667, -2.62626263,
       -2.58585859, -2.54545455, -2.50505051, -2.46464646, -2.42424242,
       -2.38383838, -2.34343434, -2.3030303 , -2.26262626, -2.22222222,
       -2.18181818, -2.14141414, -2.1010101 , -2.06060606, -2.02020202,
       -1.97979798, -1.93939394, -1.8989899 , -1.85858586, -1.81818182,
       -1.77777778, -1.73737374, -1.6969697 , -1.65656566, -1.61616162,
       -1.57575758, -1.53535354, -1.49494949, -1.45454545, -1.41414141,
       -1.37373737, -1.33333333, -1.29292929, -1.25252525, -1.21

In [39]:
r = s / w

tau_0 = 0.25 * f_c

a_3 = 2.45 / tau_0

a_4 = 2.44 * (1 - (4 / tau_0))
tau_s = tau_0 * (1 - sp.sqrt((2 * w) / d_a)) * r * (a_3 + (a_4 * sp.Abs(r) ** 3)) / (1 + (a_4 * r ** 4))
tau_s

0.25*f_c*s*(-sqrt(2)*sqrt(w/d_a) + 1)*((2.44 - 39.04/f_c)*Abs(s/w)**3 + 9.8/f_c)/(w*(s**4*(2.44 - 39.04/f_c)/w**4 + 1))

In [40]:
get_tau_s = sp.lambdify((w,s), tau_s.subs(params), 'numpy')
tau_s.subs(params)

7.5*s*(-sqrt(11)*sqrt(w)/11 + 1)*(1.13866666666667*Abs(s/w)**3 + 0.326666666666667)/(w*(1.13866666666667*s**4/w**4 + 1))

In [41]:
_, (ax1) = plt.subplots(1, 1, figsize=(10,5))
w_ = np.linspace(0,1, 100)
s_ = np.linspace(-1,1, 100)
tau = get_tau_s(w_, s_)
ax1.plot(s_, tau, color='blue', lw=2);

NameError: name 'plt' is not defined

In [42]:
import sympy as sp
w_cr, w, L_c = sp.symbols('w_cr, w, L_c')
eps_cp = w_cr / L_c
eps_p = w / L_c
sigma_ = 2 *f_t + (f_c - 2 * f_t) * sp.sqrt(1 - ((eps_cp - eps_p) / (eps_cp))**2)
sigma_

2*f_t + (f_c - 2*f_t)*sqrt(-L_c**2*(-w/L_c + w_cr/L_c)**2/w_cr**2 + 1)

In [43]:
sig_ = sp.simplify(sigma_)
sig_w = 2 * f_t + (f_c - 2 * f_t) * sp.sqrt(1 - ((w_cr - sp.Abs(w)) / (w_cr))**2)
sig_w

2*f_t + sqrt(1 - (w_cr - Abs(w))**2/w_cr**2)*(f_c - 2*f_t)

In [44]:
sig_w.diff(w)

(f_c - 2*f_t)*(w_cr - Abs(w))*(re(w)*Derivative(re(w), w) + im(w)*Derivative(im(w), w))*sign(w)/(w*w_cr**2*sqrt(1 - (w_cr - Abs(w))**2/w_cr**2))

In [45]:
params = {
    f_t : 3,
    f_c : -30,
    w_cr : 0.1
}

In [46]:
get_sig_val = sp.lambdify(w, sig_w.subs(params), 'numpy')
get_sig_val

<function _lambdifygenerated(w)>

In [47]:
_, ax = plt.subplots(1,1)
w_ = np.linspace(-0.1, 0, 100)
sig_val_ = get_sig_val(w_)
ax.plot(w_, sig_val_)

NameError: name 'plt' is not defined

In [48]:
E_c, L, w = sp.symbols('E_c, L, w')
sig_w = E_c * w / L
sig_w

E_c*w/L

In [49]:
params = {
    E_c : 28000,
    L : 20000
}

In [50]:
get_sig_w = sp.lambdify((w), sig_w.subs(params), 'numpy')
get_sig_w

<function _lambdifygenerated(w)>

In [51]:
_, ax = plt.subplots(1,1)
w_1 = np.linspace(0, 0.1, 100)
sig_val_ = get_sig_w(w_1)
ax.plot(w_1, sig_val_)

NameError: name 'plt' is not defined

In [52]:
f_t = sp.symbols(r'f_t', nonnegative=True)
c_2 = sp.Symbol('c_2', nonnegative=True)
c_1 = sp.Symbol('c_1', nonnegative=True)
f_c = sp.Symbol('f_c', nonnegative =True)
G_f, L_c = sp.symbols('G_f, L_c', nonnegative = True)

In [53]:
G_f, f_t = sp.symbols('G_f, f_t')
w_tc = 5.14 * G_f/f_t
sigma_t = f_t * (1 + ((c_1 * w)/(w_tc))**3) * sp.exp((-c_2* w)/(w_tc)) - (w/w_tc) * (1 + c_1**3) * sp.exp(-c_2)
sigma_t

f_t*(1 + 0.00736394681156715*c_1**3*f_t**3*w**3/G_f**3)*exp(-0.194552529182879*c_2*f_t*w/G_f) - 0.194552529182879*f_t*w*(c_1**3 + 1)*exp(-c_2)/G_f

In [54]:
params = {
    c_1 : 3,
    c_2 : 6.93,
    G_f : 0.5,
    f_t : 3
}

In [55]:
get_sigma_t = sp.lambdify(w, sigma_t.subs(params))
sigma_t.subs(params)

-0.0319657871382152*w + 3*(42.9465378050596*w**3 + 1)*exp(-8.08949416342412*w)

In [56]:
_, ax = plt.subplots(1,1)
w_ = np.linspace(0.1, 0.85, 100)
sig_t = get_sigma_t(w_)
ax.plot(w_, sig_t)

NameError: name 'plt' is not defined

In [57]:
sig_w_ = sp.Piecewise(
            (- f_c, w < - w_cr),
            (2 * f_t + (-f_c - 2 * f_t) * sp.sqrt(1 - ((w_cr - sp.Abs(w)) / (w_cr))**2), w < 0),
            (E_c * w / L,  w < w_cr),
            (f_t * (1 + ((c_1 * w)/(w_tc))**3) * sp.exp((-c_2* w)/(w_tc)) - (w/w_tc) * (1 + c_1**3) * sp.exp(-c_2), w > w_cr)
)

In [58]:
sig_w_

Piecewise((-f_c, w < -w_cr), (2*f_t + sqrt(1 - (w_cr - Abs(w))**2/w_cr**2)*(-f_c - 2*f_t), w < 0), (E_c*w/L, w < w_cr), (f_t*(1 + 0.00736394681156715*c_1**3*f_t**3*w**3/G_f**3)*exp(-0.194552529182879*c_2*f_t*w/G_f) - 0.194552529182879*f_t*w*(c_1**3 + 1)*exp(-c_2)/G_f, w > w_cr))

In [59]:
params = {
    c_1 : 3,
    c_2 : 6.93,
    G_f : 0.5,
    f_t : 3,
    f_c : 30,
    E_c : 28000,
    L: 20000,
    L_c : 435,
    w_cr : 0.1
}

In [60]:
get_sigma_w = sp.lambdify(w, sig_w_.subs(params), 'numpy')
sig_w_.subs(params)

Piecewise((-30, w < -0.1), (6 - 360.0*sqrt(0.01 - (0.1 - Abs(w))**2), w < 0), (7*w/5, w < 0.1), (-0.0319657871382152*w + 3*(42.9465378050596*w**3 + 1)*exp(-8.08949416342412*w), w > 0.1))

In [61]:
sig_w_d = sig_w_.diff(w)
sig_w_d

Piecewise((0, w < -w_cr), ((-f_c - 2*f_t)*(w_cr - Abs(w))*(re(w)*Derivative(re(w), w) + im(w)*Derivative(im(w), w))*sign(w)/(w*w_cr**2*sqrt(1 - (w_cr - Abs(w))**2/w_cr**2)), w < 0), (E_c/L, w < w_cr), (-0.194552529182879*c_2*f_t**2*(1 + 0.00736394681156715*c_1**3*f_t**3*w**3/G_f**3)*exp(-0.194552529182879*c_2*f_t*w/G_f)/G_f - 0.194552529182879*f_t*(c_1**3 + 1)*exp(-c_2)/G_f + 0.0220918404347014*c_1**3*f_t**4*w**2*exp(-0.194552529182879*c_2*f_t*w/G_f)/G_f**3, w > w_cr))

In [62]:
#get_sig_w_d = sp.lambdify(w, sig_w_d.subs(params), 'numpy')
#sig_w_diff.subs(params)

In [63]:
_, ax = plt.subplots(1,1)
w_ = np.linspace(-1,1, 100)
sig_w_ = get_sigma_w(w_)
#sig_w_diff = get_sig_w_diff(w_)
ax.plot(w_, sig_w_, color = 'red')
ax.fill_between(w_, sig_w_, color='red', alpha=0.2)

NameError: name 'plt' is not defined

In [64]:
#sig_w_d = get_sig_w_d(w_)
#ax.plot(w_, sig_w_d, color = 'orange')