In [1]:
%matplotlib widget
import bmcs_utils.api as bu
from bmcs_shear.shear_crack.beam_design import RCBeamDesign
from bmcs_shear.shear_crack.crack_extension import CrackExtension
from bmcs_shear.api import CrackBridgeAdv
import numpy as np
np.seterr(divide='ignore', invalid='ignore') ;

In [2]:
ce = CrackExtension()
ce.sz_cp.trait_set(x_00=400, n_m=12)
ce.sz_bd.trait_set(H=400 ,L=1000, B=50);

In [3]:
ce.X

sig_tip_1 0
sig_tip_1 0
sig_tip_1 0
sig_tip_1 0


array([4.79319751e-04, 2.00061146e+02])

In [4]:
ce.sz_cp.add_x_tip_an([400,5])
ce.X

sig_tip_1 0
sig_tip_1 0
sig_tip_1 0
sig_tip_1 42.82266881208178
sig_tip_1 0


array([  0.        , 200.06114623])

In [5]:
ce = CrackExtension()
ce.sz_cp.trait_set(x_00=400, n_m=12)
ce.sz_bd.trait_set(H=400 ,L=1000, B=50);
ce.sz_bd.csl.add_layer(
    CrackBridgeAdv(z=44, n=2, d_s=16, E = 210000, tau = 16, sig_y = 713, 
                   dowel_factor = 1, f_c = 33.3)
)
ce.sz_cp.add_x_tip_an([400,100])

In [6]:
ce.X

[22975.30555661] [16344.72112658]
sig_tip_1 2.9874406726313008
[22975.30554391] [16344.72112658]
sig_tip_1 2.9874406088627956
[22975.30541452] [16344.72112658]
sig_tip_1 2.9874406727538436
[47756.46378869] [16344.72112658]
sig_tip_1 0.3131185512817478
[22053.91456544] [16344.72112658]
sig_tip_1 2.6476634575772864
[22585.01502395] [16344.72112658]
sig_tip_1 2.2464858615208083
[25760.05103575] [16344.72112658]
sig_tip_1 0.9643225411608723
[26182.41709771] [16344.72112658]
sig_tip_1 0.9432057405154717
[24944.43750393] [16344.72112658]
sig_tip_1 3.0072038913376944
[26434.15701309] [16344.72112658]
sig_tip_1 0.971799106789357
[26255.38046189] [16344.72112658]
sig_tip_1 1.2787162783939803
[26425.52007975] [16344.72112658]
sig_tip_1 1.0900213267216137
[26411.2295768] [16344.72112658]
sig_tip_1 1.1067468229394584
[26413.96139308] [16344.72112658]
sig_tip_1 1.1038941667838067
[26413.88962896] [16344.72112658]
sig_tip_1 1.103966568843577


array([  0.28415773, 153.82736344])

In [7]:
ce.interact()