In [18]:
from bmcs_shear.dic_crack import DICGrid, DICAlignedGrid, DICCOR, DICInspector, DICCrack

In [3]:
import numpy as np
n_x, n_y = 20, 20
d_x, d_y = 14, 14
x_range = np.arange(n_x)[:-1:] * d_x
y_range = np.arange(n_y)[:-1] * d_y
y_ij, x_ij = np.meshgrid(y_range, x_range)
X_aij = np.array([x_ij, y_ij])
X_ija = np.einsum('aij->ija', X_aij)
x_range, y_range

(array([  0,  14,  28,  42,  56,  70,  84,  98, 112, 126, 140, 154, 168,
        182, 196, 210, 224, 238, 252]),
 array([  0,  14,  28,  42,  56,  70,  84,  98, 112, 126, 140, 154, 168,
        182, 196, 210, 224, 238, 252]))

In [4]:
n_x, n_y = 20, 20
d_x, d_y = 14, 14
x_range = np.arange(n_x)[::-1] * d_x
y_range = np.arange(n_y) * d_y
y_ij, x_ij = np.meshgrid(y_range, x_range)
X_aij = np.array([x_ij, y_ij])
X_ija = np.einsum('aij->ija', X_aij)
x_range, y_range

(array([266, 252, 238, 224, 210, 196, 182, 168, 154, 140, 126, 112,  98,
         84,  70,  56,  42,  28,  14,   0]),
 array([  0,  14,  28,  42,  56,  70,  84,  98, 112, 126, 140, 154, 168,
        182, 196, 210, 224, 238, 252, 266]))

In [5]:
np.arange(n_x)[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])

In [6]:
np.arange(n_x)[:-1:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18])

In [7]:
np.arange(n_y)[::1]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [8]:
n_x, n_y = 20, 20
d_x, d_y = 14, 14
y_range = np.arange(n_y)[::-1] * d_y
x_range = np.arange(n_x) * d_x
x_range, y_range

(array([  0,  14,  28,  42,  56,  70,  84,  98, 112, 126, 140, 154, 168,
        182, 196, 210, 224, 238, 252, 266]),
 array([266, 252, 238, 224, 210, 196, 182, 168, 154, 140, 126, 112,  98,
         84,  70,  56,  42,  28,  14,   0]))

In [9]:
np.arange(n_y)[::1]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [10]:
np.arange(n_x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [11]:
np.arange(n_x)[::-1]


array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])

In [12]:
print(list(reversed(np.arange(n_y)[::-1])))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


In [13]:
np.arange(n_y)[::1]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [14]:
np.arange(n_x)[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])

In [15]:
np.arange(n_y)[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])

In [16]:
n_x, n_y = 5, 5
d_x, d_y = 14, 14
x_range = np.arange(n_x)[::-1] * d_x
y_range = np.arange(n_y)[::-1] * d_y
y_ij, x_ij = np.meshgrid(y_range, x_range)
X_aij = np.array([x_ij, y_ij])
X_ija = np.einsum('aij->ija', X_aij)
x_range, y_range

(array([56, 42, 28, 14,  0]), array([56, 42, 28, 14,  0]))

In [20]:
dic_grid = DICGrid()
dic_grid.X_ija

array([[[266, 266],
        [266, 252],
        [266, 238],
        [266, 224],
        [266, 210],
        [266, 196],
        [266, 182],
        [266, 168],
        [266, 154],
        [266, 140],
        [266, 126],
        [266, 112],
        [266,  98],
        [266,  84],
        [266,  70],
        [266,  56],
        [266,  42],
        [266,  28],
        [266,  14],
        [266,   0]],

       [[252, 266],
        [252, 252],
        [252, 238],
        [252, 224],
        [252, 210],
        [252, 196],
        [252, 182],
        [252, 168],
        [252, 154],
        [252, 140],
        [252, 126],
        [252, 112],
        [252,  98],
        [252,  84],
        [252,  70],
        [252,  56],
        [252,  42],
        [252,  28],
        [252,  14],
        [252,   0]],

       [[238, 266],
        [238, 252],
        [238, 238],
        [238, 224],
        [238, 210],
        [238, 196],
        [238, 182],
        [238, 168],
        [238, 154],
        [238, 14

In [1]:
from os.path import join, expanduser
import os
import numpy as np

In [24]:
home_dir = expanduser('~')
data_dir = join(home_dir,'simdb','data','shear_zone','B8_TV1')
data_dir

'C:\\Users\\fahad\\simdb\\data\\shear_zone\\B8_TV1'

In [52]:
files = [join(data_dir, each)
               for each in sorted(os.listdir(data_dir))
               if each.endswith('.csv')]
u_tpa = np.array([
    np.loadtxt(csv_file, dtype=float,
                       skiprows=1, delimiter=',', usecols=(2,3), unpack=False)
for csv_file in files
], dtype=np.float_)
n_t, n_e, n_a = u_tpa.shape  # get the dimensions of the time and entry dimensions
n_x, n_y = 56, 13
u_tjia = u_tpa.reshape(n_t, n_x, n_y, 2)
u_tija = np.einsum('tjia->tija', u_tjia)

In [53]:
np.shape(u_tpa)

(15, 728, 2)

In [54]:
u_tjia[1]

array([[[ 0.016, -0.115],
        [ 0.018, -0.115],
        [ 0.019, -0.117],
        ...,
        [ 0.049, -0.122],
        [ 0.054, -0.124],
        [ 0.058, -0.122]],

       [[ 0.01 , -0.117],
        [ 0.017, -0.119],
        [ 0.021, -0.123],
        ...,
        [ 0.053, -0.126],
        [ 0.051, -0.128],
        [ 0.056, -0.129]],

       [[ 0.016, -0.124],
        [ 0.014, -0.124],
        [ 0.019, -0.127],
        ...,
        [ 0.042, -0.132],
        [ 0.053, -0.133],
        [ 0.055, -0.13 ]],

       ...,

       [[ 0.02 , -0.264],
        [ 0.021, -0.266],
        [ 0.021, -0.267],
        ...,
        [ 0.019, -0.27 ],
        [ 0.019, -0.266],
        [ 0.019, -0.265]],

       [[ 0.017, -0.266],
        [ 0.02 , -0.266],
        [ 0.019, -0.264],
        ...,
        [ 0.02 , -0.268],
        [ 0.02 , -0.267],
        [ 0.017, -0.269]],

       [[ 0.018, -0.265],
        [ 0.022, -0.266],
        [ 0.018, -0.265],
        ...,
        [ 0.019, -0.268],
        [ 0.019

In [55]:
home_dir = expanduser('~')
data_dir = join(home_dir,'simdb','data','shear_zone','B8_TV1')
data_dir

'C:\\Users\\fahad\\simdb\\data\\shear_zone\\B8_TV1'

In [56]:
results = [join(data_dir,each) 
           for each in sorted(os.listdir(data_dir)) 
           if each.endswith('.csv')]
results

['C:\\Users\\fahad\\simdb\\data\\shear_zone\\B8_TV1\\Load_000_KN.csv',
 'C:\\Users\\fahad\\simdb\\data\\shear_zone\\B8_TV1\\Load_012_KN.csv',
 'C:\\Users\\fahad\\simdb\\data\\shear_zone\\B8_TV1\\Load_024_KN.csv',
 'C:\\Users\\fahad\\simdb\\data\\shear_zone\\B8_TV1\\Load_038_KN.csv',
 'C:\\Users\\fahad\\simdb\\data\\shear_zone\\B8_TV1\\Load_052_KN.csv',
 'C:\\Users\\fahad\\simdb\\data\\shear_zone\\B8_TV1\\Load_063_KN.csv',
 'C:\\Users\\fahad\\simdb\\data\\shear_zone\\B8_TV1\\Load_075_KN.csv',
 'C:\\Users\\fahad\\simdb\\data\\shear_zone\\B8_TV1\\Load_087_KN.csv',
 'C:\\Users\\fahad\\simdb\\data\\shear_zone\\B8_TV1\\Load_101_KN.csv',
 'C:\\Users\\fahad\\simdb\\data\\shear_zone\\B8_TV1\\Load_112_KN.csv',
 'C:\\Users\\fahad\\simdb\\data\\shear_zone\\B8_TV1\\Load_126_KN.csv',
 'C:\\Users\\fahad\\simdb\\data\\shear_zone\\B8_TV1\\Load_137_KN.csv',
 'C:\\Users\\fahad\\simdb\\data\\shear_zone\\B8_TV1\\Load_152_KN.csv',
 'C:\\Users\\fahad\\simdb\\data\\shear_zone\\B8_TV1\\Load_162_KN.csv',
 'C:\\

In [57]:
u_tija[1] - u_tija[0]

array([[[ 0.016, -0.115],
        [ 0.01 , -0.117],
        [ 0.016, -0.124],
        ...,
        [ 0.02 , -0.264],
        [ 0.017, -0.266],
        [ 0.018, -0.265]],

       [[ 0.018, -0.115],
        [ 0.017, -0.119],
        [ 0.014, -0.124],
        ...,
        [ 0.021, -0.266],
        [ 0.02 , -0.266],
        [ 0.022, -0.266]],

       [[ 0.019, -0.117],
        [ 0.021, -0.123],
        [ 0.019, -0.127],
        ...,
        [ 0.021, -0.267],
        [ 0.019, -0.264],
        [ 0.018, -0.265]],

       ...,

       [[ 0.049, -0.122],
        [ 0.053, -0.126],
        [ 0.042, -0.132],
        ...,
        [ 0.019, -0.27 ],
        [ 0.02 , -0.268],
        [ 0.019, -0.268]],

       [[ 0.054, -0.124],
        [ 0.051, -0.128],
        [ 0.053, -0.133],
        ...,
        [ 0.019, -0.266],
        [ 0.02 , -0.267],
        [ 0.019, -0.268]],

       [[ 0.058, -0.122],
        [ 0.056, -0.129],
        [ 0.055, -0.13 ],
        ...,
        [ 0.019, -0.265],
        [ 0.017

In [64]:
# u_tija[1][0]

array([[ 0.016, -0.115],
       [ 0.01 , -0.117],
       [ 0.016, -0.124],
       [ 0.01 , -0.127],
       [ 0.013, -0.132],
       [ 0.014, -0.137],
       [ 0.017, -0.139],
       [ 0.013, -0.146],
       [ 0.014, -0.15 ],
       [ 0.014, -0.151],
       [ 0.015, -0.157],
       [ 0.007, -0.164],
       [ 0.001, -0.169],
       [ 0.001, -0.173],
       [ 0.002, -0.178],
       [ 0.003, -0.182],
       [ 0.005, -0.186],
       [ 0.003, -0.19 ],
       [ 0.004, -0.191],
       [ 0.005, -0.194],
       [ 0.007, -0.197],
       [ 0.007, -0.2  ],
       [ 0.007, -0.2  ],
       [ 0.007, -0.206],
       [ 0.007, -0.207],
       [ 0.009, -0.21 ],
       [ 0.009, -0.212],
       [ 0.009, -0.216],
       [ 0.007, -0.218],
       [ 0.008, -0.22 ],
       [ 0.006, -0.225],
       [ 0.006, -0.229],
       [ 0.008, -0.232],
       [ 0.006, -0.234],
       [ 0.008, -0.235],
       [ 0.011, -0.241],
       [ 0.011, -0.242],
       [ 0.011, -0.247],
       [ 0.011, -0.25 ],
       [ 0.012, -0.251],


In [59]:
x_range = np.arange(n_x)[::-1] * 23
#y_range = np.arange(n_y) * self.d_y #for beams having grid number from right to left
y_range = np.arange(n_y)[::-1] * 23 #for beams having grid number from top to bottom
y_ij, x_ij = np.meshgrid(y_range, x_range)
X_aij = np.array([x_ij, y_ij])
X_ija = np.einsum('aij->ija', X_aij)
X_ija[0]

array([[1265,  276],
       [1265,  253],
       [1265,  230],
       [1265,  207],
       [1265,  184],
       [1265,  161],
       [1265,  138],
       [1265,  115],
       [1265,   92],
       [1265,   69],
       [1265,   46],
       [1265,   23],
       [1265,    0]])

In [60]:
x_range = np.arange(n_x)[::-1] * 23
y_range = np.arange(n_y) * 23 #for beams having grid number from right to left
#y_range = np.arange(n_y)[::-1] * 23 #for beams having grid number from top to bottom
y_ij, x_ij = np.meshgrid(y_range, x_range)
X_aij = np.array([x_ij, y_ij])
X_ija = np.einsum('aij->ija', X_aij)
X_ija

array([[[1265,    0],
        [1265,   23],
        [1265,   46],
        ...,
        [1265,  230],
        [1265,  253],
        [1265,  276]],

       [[1242,    0],
        [1242,   23],
        [1242,   46],
        ...,
        [1242,  230],
        [1242,  253],
        [1242,  276]],

       [[1219,    0],
        [1219,   23],
        [1219,   46],
        ...,
        [1219,  230],
        [1219,  253],
        [1219,  276]],

       ...,

       [[  46,    0],
        [  46,   23],
        [  46,   46],
        ...,
        [  46,  230],
        [  46,  253],
        [  46,  276]],

       [[  23,    0],
        [  23,   23],
        [  23,   46],
        ...,
        [  23,  230],
        [  23,  253],
        [  23,  276]],

       [[   0,    0],
        [   0,   23],
        [   0,   46],
        ...,
        [   0,  230],
        [   0,  253],
        [   0,  276]]])