# 2D Crack propagation in a bended beam

 - @todo: Plot the residual value
 - @todo: State dependencies - recalculate upon material parameter change

In [3]:
%matplotlib widget
import bmcs_utils.api as bu
from bmcs_shear.shear_crack.crack_propagation import CrackPropagation
ce = CrackPropagation(n_seg=500)
ce.sz_bd.cmm.trait_set(tau_1 = 4, s_1 = 0.2, tau_2 = 3, tau_3 = 2, s_2 = 1.4, s_3 = 5)
ce.sz_bd.cmm.trait_set(f_c = 35.6, f_t = 2.85, d_a = 22)
ce.sz_bd.Rectangle = True
ce.sz_bd.trait_set(H=1000, B=300, L=5600)
ce.sz_cp.trait_set(x_00=ce.sz_bd.L * 0.5, n_m = 15)
ce.sz_cp.sz_ctr.trait_set(ell = 1)
ce.sz_bd.cross_section_layout.reinforcement.z_j[0] = 80
ce.sz_bd.cross_section_layout.reinforcement.A_j[0] = 710 * 2 + 1030 * 2 #2 n32 + 2 n36
ce.sz_bd.cross_section_layout.reinforcement.E_j[0] = 210000 / 100

\begin{align}
\sigma_\mathrm{F} = E w / L_\mathrm{eff}
\end{align}

In [4]:
bu.InteractiveWindow([ce, ce.sz_bd, ce.sz_bd.cross_section_layout,
                      ce.sz_stress_profile,
                      ce.sz_bd.cmm, ce.sz_bd.smm, ce.sz_cp, ce.sz_cp.sz_ctr]).interact()

<lambdifygenerated-30>:2: RuntimeWarning: invalid value encountered in sqrt
  return (select([less_equal(w, 0),True], [0,0.25*f_c*s*(-sqrt(2)*sqrt(w/d_a) + 1)*((2.44 - 39.04/f_c)*abs(s/w)**3 + 9.8/f_c)/(w*(s**4*(2.44 - 39.04/f_c)/w**4 + 1))], default=nan))


<lambdifygenerated-30>:2: RuntimeWarning: invalid value encountered in sqrt
  return (select([less_equal(w, 0),True], [0,0.25*f_c*s*(-sqrt(2)*sqrt(w/d_a) + 1)*((2.44 - 39.04/f_c)*abs(s/w)**3 + 9.8/f_c)/(w*(s**4*(2.44 - 39.04/f_c)/w**4 + 1))], default=nan))


In [ ]:
import numpy as np
S_Lb = ce.sz_stress_profile.S_Lb
S_La = ce.sz_stress_profile.S_La
idx = np.argmax(S_Lb[...,0])

In [ ]:
S_Lb[idx,:], S_La[idx,:]

In [ ]:
ce.sz_cp.T_Mab[idx,...]

In [ ]:
np.einsum('i,i', S_Lb[idx,:], S_Lb[idx,:])

In [ ]:
np.einsum('i,i', S_La[idx,:], S_La[idx,:])

Todo:

 - include the reinforcement material law - partially done
   (but for strain-based material law) - replace with the crack bridge law
 - transformation of the crack bridging force to the global coordinates
 - include the dowel effect

In [ ]:
#ce.sz_cp._get_norm_n_vec_L()

In [ ]:
#ce.sz_cp._get_x_Ka()

In [ ]:
#ce.sz_stress_profile._get_S_La()

In [ ]:
#ce.sz_stress_profile._get_F_La()

In [ ]:
#ce.sz_stress_profile._get_F_ag()

In [ ]:
#ce.sz_stress_profile._get_u_Lb()

In [ ]:
#ce.sz_stress_profile._get_S_Lb()[:,1]

In [ ]:
ce.sz_stress_profile.u_La[...,1]

In [ ]:
ce.sz_cp.x_Ka

In [ ]:
ce.sz_stress_profile.u_La[...,1]

In [ ]:
ce.sz_stress_profile.normalized_def #[...,1]

In [ ]:
ce.sz_stress_profile.tau_exp

In [ ]:
ce.sz_stress_profile.F_Na[...,0]

In [ ]:
ce.sz_ctr._get_x_rot_ak()

In [ ]:
ce.sz_stress_profile._get_M()

In [ ]:
ce.sz_stress_profile._get_S_La()

In [ ]:
ce.sz_stress_profile._get_F_La()

In [ ]:
ce.sz_cp.norm_n_vec_L[:]

In [ ]:
ce.sz_stress_profile.F_Na

In [ ]:
ce.sz_stress_profile.F_La[:,1]

In [ ]:
ce.sz_stress_profile.S_La[:,1]

In [5]:
import numpy as np
np.sum(ce.sz_stress_profile._get_F_La())

6556.751788039808

In [6]:
ce.sz_stress_profile._get_F_La() / (ce.sz_bd.B * 920) * 1000

array([[ 1.90358022e-02,  1.03880631e-02],
       [ 1.90428189e-02,  1.03892545e-02],
       [ 1.90498381e-02,  1.03904462e-02],
       ...,
       [-1.84390276e+01,  0.00000000e+00],
       [-1.86446069e+01,  0.00000000e+00],
       [-1.88501862e+01,  0.00000000e+00]])

In [7]:
#ce.v_n  / ce.sz_bd.L
v_ = np.array(ce.v_n)
v_ / ce.sz_bd.L
s_L = v_ / ce.sz_bd.cmm.L_c
s_L

array([0.        , 0.00057115, 0.00057711, 0.00057827, 0.00057944,
       0.00058062, 0.00058181, 0.000583  , 0.00058419, 0.00058539,
       0.00058656, 0.00058776, 0.00058898, 0.0005902 , 0.00059141,
       0.00059263, 0.00059386, 0.0005951 , 0.00059634, 0.00059759,
       0.00059885, 0.00060009, 0.00060135, 0.00060262, 0.0006039 ,
       0.00060517, 0.00060646, 0.00060775, 0.00060905, 0.00061036,
       0.00061164, 0.00061296, 0.00061427, 0.0006156 , 0.00061692,
       0.00061826, 0.00061961, 0.00062096, 0.00062232, 0.00062366,
       0.00062503, 0.0006264 , 0.00062777, 0.00062915, 0.00063054,
       0.00063194, 0.00063335, 0.00063476, 0.00063616, 0.00063759,
       0.00063902, 0.00064046, 0.00064191, 0.00064336, 0.00064479,
       0.00064625, 0.00064772, 0.0006492 , 0.00065068, 0.00065217,
       0.00065367, 0.00065517, 0.00065667, 0.00065819, 0.0006597 ,
       0.00066123, 0.00066274, 0.00066427, 0.00066582, 0.00066738,
       0.00066895, 0.00067053, 0.00067212, 0.00067371, 0.00067

In [8]:
F_ = np.array(ce.F_beam)
F_

array([     0.        ,  91886.02872923,  92063.55819479,  92245.02361833,
        92427.20320488,  92611.66589558,  92796.88281237,  92982.85685435,
        93169.59212554,  93357.09641278,  93536.07249611,  93723.42396978,
        93913.13473442,  94103.63130907,  94290.29094044,  94480.84404033,
        94672.15394412,  94864.24557053,  95057.15384396,  95252.33958784,
        95448.34598053,  95640.58663977,  95836.77198012,  96033.72677815,
        96232.97275404,  96430.04133526,  96630.94753944,  96832.71212624,
        97035.33799182,  97238.8315669 ,  97435.77885516,  97640.92807107,
        97844.08133218,  98050.9690565 ,  98255.92881028,  98464.57085488,
        98674.12107856,  98884.58295559,  99095.96224691,  99301.0477449 ,
        99514.18548756,  99728.25507737,  99939.06175004, 100153.58858868,
       100369.095509  , 100586.87528853, 100805.62255254, 101025.34004045,
       101240.5083644 , 101462.11191334, 101684.70714771, 101908.30447083,
       102132.90394169, 1

In [9]:
tau_exp = F_ / (ce.sz_bd.B * 920 )
tau_exp

array([0.        , 0.33292039, 0.33356362, 0.3342211 , 0.33488117,
       0.33554951, 0.33622059, 0.33689441, 0.33757099, 0.33825035,
       0.33889881, 0.33957762, 0.34026498, 0.34095519, 0.34163149,
       0.3423219 , 0.34301505, 0.34371103, 0.34440998, 0.34511717,
       0.34582734, 0.34652386, 0.34723468, 0.34794829, 0.34867019,
       0.34938421, 0.35011213, 0.35084316, 0.35157731, 0.35231461,
       0.35302818, 0.35377148, 0.35450754, 0.35525713, 0.35599974,
       0.35675569, 0.35751493, 0.35827747, 0.35904334, 0.3597864 ,
       0.36055864, 0.36133426, 0.36209805, 0.36287532, 0.36365614,
       0.3644452 , 0.36523776, 0.36603384, 0.36681344, 0.36761635,
       0.36842285, 0.36923299, 0.37004675, 0.3708642 , 0.37165524,
       0.37247528, 0.37330335, 0.37412573, 0.37496119, 0.37580047,
       0.37664361, 0.37749061, 0.37831838, 0.37916939, 0.38000399,
       0.38085112, 0.3816738 , 0.38250173, 0.38334301, 0.38418248,
       0.38502016, 0.38585603, 0.38669012, 0.38752242, 0.38835

In [10]:
import matplotlib.pylab as plt
_, (ax1) = plt.subplots(1, 1, figsize=(12,7))
ax1.plot(s_L, tau_exp, color='blue', lw=2);
ax1.set_xlabel(r'$v/L$'); ax1.set_ylabel(r'$\tau_{exp}$');

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …