# 2D Crack propagation in a bended beam

 - @todo: Plot the residual value
 - @todo: State dependencies - recalculate upon material parameter change

In [1]:
%matplotlib widget
import bmcs_utils.api as bu
from bmcs_shear.shear_crack.crack_propagation import CrackPropagation
ce = CrackPropagation(n_seg=200)
ce.sz_bd.cmm.trait_set(tau_1 = 4, s_1 = 0.2, tau_2 = 3, tau_3 = 2, s_2 = 1.4, s_3 = 5)
ce.sz_bd.cmm.trait_set(f_c = 37.9, f_t = 3.06, d_a = 22)
ce.sz_bd.Rectangle = True
ce.sz_bd.trait_set(H=250, B=75, L=1400)
ce.sz_cp.trait_set(x_00=ce.sz_bd.L * 0.7, n_m = 15)
ce.sz_cp.sz_ctr.trait_set(ell = 1)
ce.sz_bd.cross_section_layout.reinforcement.z_j[0] = 20
ce.sz_bd.cross_section_layout.reinforcement.A_j[0] = 50.3 * 4
ce.sz_bd.cross_section_layout.reinforcement.E_j[0] = 210000 / 100

\begin{align}
\sigma_\mathrm{F} = E w / L_\mathrm{eff}
\end{align}

In [2]:
bu.InteractiveWindow([ce, ce.sz_bd, ce.sz_bd.cross_section_layout, 
                      ce.sz_stress_profile, 
                      ce.sz_bd.cmm, ce.sz_bd.smm, ce.sz_cp, ce.sz_cp.sz_ctr]).interact()

<lambdifygenerated-24>:2: RuntimeWarning: invalid value encountered in sqrt
  return (select([less_equal(w, 0),True], [0,0.25*f_c*s*(-sqrt(2)*sqrt(w/d_a) + 1)*((2.44 - 39.04/f_c)*abs(s/w)**3 + 9.8/f_c)/(w*(s**4*(2.44 - 39.04/f_c)/w**4 + 1))], default=nan))


In [ ]:
import numpy as np
S_Lb = ce.sz_stress_profile.S_Lb
S_La = ce.sz_stress_profile.S_La
idx = np.argmax(S_Lb[...,0])

In [ ]:
S_Lb[idx,:], S_La[idx,:]

In [ ]:
ce.sz_cp.T_Mab[idx,...]

In [ ]:
np.einsum('i,i', S_Lb[idx,:], S_Lb[idx,:])

In [ ]:
np.einsum('i,i', S_La[idx,:], S_La[idx,:])

Todo:

 - include the reinforcement material law - partially done 
   (but for strain-based material law) - replace with the crack bridge law
 - transformation of the crack bridging force to the global coordinates
 - include the dowel effect 

In [ ]:
#ce.sz_cp._get_norm_n_vec_L()

In [ ]:
#ce.sz_cp._get_x_Ka()

In [ ]:
#ce.sz_stress_profile._get_S_La()

In [ ]:
#ce.sz_stress_profile._get_F_La()

In [ ]:
#ce.sz_stress_profile._get_F_ag()

In [ ]:
#ce.sz_stress_profile._get_u_Lb()

In [ ]:
#ce.sz_stress_profile._get_S_Lb()[:,1]

In [ ]:
ce.sz_stress_profile.u_La[...,1]

In [ ]:
ce.sz_cp.x_Ka

In [ ]:
ce.sz_stress_profile.u_La[...,1]

In [ ]:
#ce.sz_stress_profile.normalized_def #[...,1]

In [ ]:
#ce.sz_stress_profile.tau_exp

In [ ]:
ce.sz_stress_profile.F_Na[...,0]

In [ ]:
ce.sz_ctr._get_x_rot_ak()

In [11]:
import numpy as np
v_ = np.array(ce.v_n)
v_ / ce.sz_bd.L
s_L = v_ / ce.sz_bd.cmm.L_c
s_L

array([0.        , 0.00037018, 0.00041446, 0.00041797, 0.00042181,
       0.00042495, 0.00042869, 0.00043274, 0.00043594, 0.00043925,
       0.00044345, 0.00044723, 0.00045105, 0.00045489, 0.00045878,
       0.00046269, 0.00046663, 0.00047062, 0.00047463, 0.00047868,
       0.00048276, 0.00048687, 0.00049102, 0.00049521, 0.00049942,
       0.00050367, 0.00050795, 0.00051224, 0.00051661, 0.00052099,
       0.0005254 , 0.00052985, 0.00053433, 0.00053884, 0.00054339,
       0.00054797, 0.00055258, 0.00055723, 0.00056191, 0.00056662,
       0.00057137, 0.00057623, 0.00058097, 0.00058582, 0.0005907 ,
       0.00059562, 0.00060057, 0.00060556, 0.00061059, 0.00061565,
       0.00062074, 0.00062587, 0.00063104, 0.00063624, 0.00064149,
       0.00064676, 0.00065208, 0.00065743, 0.00066283, 0.00066826,
       0.00067373, 0.00067924, 0.0006848 , 0.00069039, 0.00069602,
       0.0007017 , 0.00070742, 0.00071319, 0.00071899, 0.00072485,
       0.00073075, 0.00073669, 0.00074268, 0.00074872, 0.00075

In [12]:
F_ = np.array(ce.F_beam)

In [13]:
tau_exp = F_ / (ce.sz_bd.B * 230 )
tau_exp

array([0.        , 0.91853397, 0.9242807 , 0.92992721, 0.93654507,
       0.94132065, 0.94626962, 0.95279192, 0.95702217, 0.96148938,
       0.96655883, 0.97134264, 0.97601162, 0.98056388, 0.9850183 ,
       0.98931165, 0.99350427, 0.99758906, 1.00152174, 1.00534394,
       1.00903883, 1.01260692, 1.01604769, 1.01936695, 1.02253896,
       1.02560185, 1.02851927, 1.03126065, 1.03393635, 1.03646165,
       1.03882717, 1.04107844, 1.0431941 , 1.0451644 , 1.04700296,
       1.04870379, 1.05026826, 1.05169602, 1.05299104, 1.05414024,
       1.0551566 , 1.05603872, 1.05677876, 1.05738488, 1.05785711,
       1.05819373, 1.05839218, 1.0584594 , 1.05838999, 1.05818807,
       1.05785136, 1.05738425, 1.05678659, 1.05605613, 1.05519772,
       1.05420812, 1.05309478, 1.05184965, 1.05048196, 1.04898879,
       1.0473717 , 1.04562967, 1.04377159, 1.04178982, 1.03969196,
       1.03747612, 1.03514372, 1.0326964 , 1.03013713, 1.02746684,
       1.0246849 , 1.02179509, 1.0188007 , 1.01569875, 1.01249

In [14]:
import matplotlib.pylab as plt
_, (ax1) = plt.subplots(1, 1, figsize=(12,7))
ax1.plot(s_L, tau_exp, color='blue', lw=2);
ax1.set_xlabel(r'$v/L$'); ax1.set_ylabel(r'$\tau_{exp}$');

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [15]:
ce.sz_stress_profile.u_La[...,1] / ce.sz_bd.L

array([ 6.61060130e-05,  6.61051616e-05,  6.61043102e-05, ...,
       -1.47742490e-07, -1.47797912e-07, -1.47853335e-07])