# 2D Crack propagation in a bended beam

 - @todo: Plot the residual value
 - @todo: State dependencies - recalculate upon material parameter change

In [1]:
%matplotlib widget
import bmcs_utils.api as bu
from bmcs_shear.shear_crack.crack_propagation import CrackPropagation
ce = CrackPropagation(n_seg=350)
ce.sz_bd.cmm.trait_set(tau_1 = 4, s_1 = 0.2, tau_2 = 3, tau_3 = 2, s_2 = 1.4, s_3 = 5)
ce.sz_bd.cmm.trait_set(f_c = 36, f_t = 3.02, d_a = 22)
ce.sz_bd.Rectangle = True
ce.sz_bd.trait_set(H=500, B=150, L=2800)
ce.sz_cp.trait_set(x_00=ce.sz_bd.L * 0.3, n_m = 15)
ce.sz_cp.sz_ctr.trait_set(ell = 1)
ce.sz_bd.cross_section_layout.reinforcement.z_j[0] = 40
ce.sz_bd.cross_section_layout.reinforcement.A_j[0] = 201 * 4
ce.sz_bd.cross_section_layout.reinforcement.E_j[0] = 210000 / 100

\begin{align}
\sigma_\mathrm{F} = E w / L_\mathrm{eff}
\end{align}

In [19]:
bu.InteractiveWindow([ce, ce.sz_bd, ce.sz_bd.cross_section_layout, 
                      ce.sz_stress_profile, 
                      ce.sz_bd.cmm, ce.sz_bd.smm, ce.sz_cp, ce.sz_cp.sz_ctr]).interact()

<lambdifygenerated-24>:2: RuntimeWarning: invalid value encountered in sqrt
  return (select([less_equal(w, 0),True], [0,0.25*f_c*s*(-sqrt(2)*sqrt(w/d_a) + 1)*((2.44 - 39.04/f_c)*abs(s/w)**3 + 9.8/f_c)/(w*(s**4*(2.44 - 39.04/f_c)/w**4 + 1))], default=nan))


In [3]:
import numpy as np
S_Lb = ce.sz_stress_profile.S_Lb
S_La = ce.sz_stress_profile.S_La
idx = np.argmax(S_Lb[...,0])

In [4]:
S_Lb[idx,:], S_La[idx,:]

(array([4.42837489e+02, 3.21533736e-02]),
 array([4.42837489e+02, 3.21533736e-02]))

In [5]:
ce.sz_cp.T_Mab[idx,...]

array([[1., 0.],
       [0., 1.]])

In [6]:
np.einsum('i,i', S_Lb[idx,:], S_Lb[idx,:])

196105.0422681713

In [7]:
np.einsum('i,i', S_La[idx,:], S_La[idx,:])

196105.0422681713

Todo:

 - include the reinforcement material law - partially done 
   (but for strain-based material law) - replace with the crack bridge law
 - transformation of the crack bridging force to the global coordinates
 - include the dowel effect 

In [8]:
#ce.sz_cp._get_norm_n_vec_L()

In [9]:
#ce.sz_cp._get_x_Ka()

In [10]:
#ce.sz_stress_profile._get_S_La()

In [11]:
#ce.sz_stress_profile._get_F_La()

In [12]:
#ce.sz_stress_profile._get_F_ag()

In [13]:
#ce.sz_stress_profile._get_u_Lb()

In [14]:
#ce.sz_stress_profile._get_S_Lb()[:,1]

In [15]:
ce.sz_stress_profile.u_La[...,1]

array([ 4.34667513e-06,  4.28413305e-06,  4.22159096e-06,  4.15904887e-06,
        4.09650679e-06,  4.03396470e-06,  3.97142260e-06,  3.90888049e-06,
        3.84633841e-06,  3.78379634e-06,  3.72125425e-06,  3.65871216e-06,
        3.59617007e-06,  3.53362799e-06,  3.47108590e-06,  3.40854380e-06,
        3.34600171e-06,  3.28345962e-06,  3.22091753e-06,  3.15837546e-06,
        3.09583337e-06,  3.03329127e-06,  2.97074919e-06,  2.90820712e-06,
        2.84566503e-06,  2.78312292e-06,  2.72058082e-06,  2.65803874e-06,
        2.59549665e-06,  2.53295456e-06,  2.47041249e-06,  2.40787040e-06,
        2.34532831e-06,  2.28278623e-06,  2.22024414e-06,  2.15770205e-06,
        2.09515996e-06,  2.03261786e-06,  1.97007577e-06,  1.90753369e-06,
        1.84499160e-06,  1.78244952e-06,  1.71990743e-06,  1.65736535e-06,
        1.59482325e-06,  1.53228115e-06,  1.46973908e-06,  1.40719699e-06,
        1.34465489e-06,  1.28211281e-06,  1.21957072e-06,  1.15702863e-06,
        1.09448655e-06,  

In [16]:
ce.sz_cp.x_Ka

array([[840.        ,   0.        ],
       [840.        ,   3.57142857],
       [840.        ,   7.14285714],
       [840.        ,  10.71428571],
       [840.        ,  14.28571429],
       [840.        ,  17.85714286],
       [840.        ,  21.42857143],
       [840.        ,  25.        ],
       [840.        ,  28.57142857],
       [840.        ,  32.14285714],
       [840.        ,  35.71428571],
       [840.        ,  39.28571429],
       [840.        ,  42.85714286],
       [840.        ,  46.42857143],
       [840.        ,  50.        ],
       [840.        ,  53.57142857],
       [840.        ,  57.14285714],
       [840.        ,  60.71428571],
       [840.        ,  64.28571429],
       [840.        ,  67.85714286],
       [840.        ,  71.42857143],
       [840.        ,  75.        ],
       [840.        ,  78.57142857],
       [840.        ,  82.14285714],
       [840.        ,  85.71428571],
       [840.        ,  89.28571429],
       [840.        ,  92.85714286],
 

In [17]:
ce.sz_stress_profile.u_La[...,1]

array([ 4.34667513e-06,  4.28413305e-06,  4.22159096e-06,  4.15904887e-06,
        4.09650679e-06,  4.03396470e-06,  3.97142260e-06,  3.90888049e-06,
        3.84633841e-06,  3.78379634e-06,  3.72125425e-06,  3.65871216e-06,
        3.59617007e-06,  3.53362799e-06,  3.47108590e-06,  3.40854380e-06,
        3.34600171e-06,  3.28345962e-06,  3.22091753e-06,  3.15837546e-06,
        3.09583337e-06,  3.03329127e-06,  2.97074919e-06,  2.90820712e-06,
        2.84566503e-06,  2.78312292e-06,  2.72058082e-06,  2.65803874e-06,
        2.59549665e-06,  2.53295456e-06,  2.47041249e-06,  2.40787040e-06,
        2.34532831e-06,  2.28278623e-06,  2.22024414e-06,  2.15770205e-06,
        2.09515996e-06,  2.03261786e-06,  1.97007577e-06,  1.90753369e-06,
        1.84499160e-06,  1.78244952e-06,  1.71990743e-06,  1.65736535e-06,
        1.59482325e-06,  1.53228115e-06,  1.46973908e-06,  1.40719699e-06,
        1.34465489e-06,  1.28211281e-06,  1.21957072e-06,  1.15702863e-06,
        1.09448655e-06,  

In [20]:
ce.sz_stress_profile.normalized_def #[...,1]

AttributeError: 'SZStressProfile' object has no attribute 'normalized_def'

In [21]:
ce.sz_stress_profile.tau_exp

AttributeError: 'SZStressProfile' object has no attribute 'tau_exp'

In [ ]:
ce.sz_stress_profile.F_Na[...,0]

In [ ]:
ce.sz_ctr._get_x_rot_ak()

In [22]:
import numpy as np
v_ = np.array(ce.v_n)
v_ / ce.sz_bd.L
s_L = v_ / ce.sz_bd.cmm.L_c
s_L

array([0.        , 0.00084901, 0.00087666, 0.00088031, 0.00088399,
       0.00088734, 0.00089108, 0.00089464, 0.0008983 , 0.00090214,
       0.00090601, 0.00090991, 0.00091384, 0.00091781, 0.00092087,
       0.00092491, 0.00092821, 0.000932  , 0.00093613, 0.00093967,
       0.00094387, 0.00094811, 0.00095128, 0.00095518, 0.00095952,
       0.00096302, 0.00096743, 0.00097093, 0.00097491, 0.00097943,
       0.00098399, 0.0009886 , 0.00099098, 0.00099565, 0.00100037,
       0.00100513, 0.00100727, 0.00101141, 0.00101555, 0.00102046,
       0.00102387, 0.00102916, 0.0010339 , 0.00103647, 0.0010407 ,
       0.00104586, 0.00104922, 0.00105445, 0.00105779, 0.00106312,
       0.00106644, 0.00107185, 0.00107732, 0.00107952, 0.00108507,
       0.00108833, 0.00109275, 0.00109844, 0.00110167, 0.00110614,
       0.00111063, 0.00111522, 0.00112114, 0.00112422, 0.00112881,
       0.00113336, 0.00113796, 0.00114412, 0.00114721, 0.00115183,
       0.00115651, 0.00116119, 0.00116589, 0.00117059, 0.00117

In [23]:
F_ = np.array(ce.F_beam)

In [24]:
tau_exp = F_ / (ce.sz_bd.B * 460 )
tau_exp

array([0.        , 0.30210734, 0.30328184, 0.30446613, 0.30566031,
       0.30672055, 0.30792224, 0.3090348 , 0.31017604, 0.31136507,
       0.31255043, 0.31373216, 0.31491032, 0.31573805, 0.31690571,
       0.31806988, 0.31895188, 0.31999945, 0.32114969, 0.32207132,
       0.32321276, 0.32435098, 0.32509396, 0.32608098, 0.32720454,
       0.32801849, 0.32913295, 0.3299125 , 0.33084248, 0.33194313,
       0.33304092, 0.33413593, 0.33445024, 0.33552969, 0.33660868,
       0.33768504, 0.33786467, 0.33869679, 0.3395108 , 0.34056351,
       0.34110265, 0.34214545, 0.34318594, 0.34340035, 0.34414086,
       0.34516328, 0.34558681, 0.34659887, 0.34698203, 0.34798352,
       0.34832815, 0.34931893, 0.3503079 , 0.35025284, 0.35122729,
       0.35147046, 0.35206063, 0.35301831, 0.35320406, 0.35375441,
       0.35429178, 0.35483977, 0.35533375, 0.35583065, 0.3563242 ,
       0.35678955, 0.35724876, 0.35814773, 0.35813146, 0.35854605,
       0.35895521, 0.3593491 , 0.3597294 , 0.3600929 , 0.36045

In [25]:
import matplotlib.pylab as plt
_, (ax1) = plt.subplots(1, 1, figsize=(12,7))
ax1.plot(s_L, tau_exp, color='blue', lw=2);
ax1.set_xlabel(r'$v/L$'); ax1.set_ylabel(r'$\tau_{exp}$');

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …