In [1]:
import pandas as pd
import numpy as np

In [2]:
load_step_191_data_frame = pd.read_csv('C:/Users/fahad/OneDrive/Documents/GOM Results/Load 191 KN.csv',sep = ',',header = 0,
                            usecols = [0,2,4]) #np.array()
load_step_191_data_frame

Element Property  Actual
0        Point 2       dX   1.651
1        Point 2       dY  -5.978
2        Point 3       dX   1.653
3        Point 3       dY  -6.090
4        Point 4       dX   1.651
...          ...      ...     ...
1721   Point 862       dY  -9.534
1722   Point 863       dX   1.647
1723   Point 863       dY  -5.866
1724   Point 864       dX  -0.801
1725   Point 864       dY  -9.623

[1726 rows x 3 columns]

In [3]:
dx_data_frame = load_step_191_data_frame.iloc[::2]
dx_data_frame

Element Property  Actual
0        Point 2       dX   1.651
2        Point 3       dX   1.653
4        Point 4       dX   1.651
6        Point 5       dX   1.658
8        Point 6       dX   1.598
...          ...      ...     ...
1716   Point 860       dX  -0.840
1718   Point 861       dX  -0.827
1720   Point 862       dX  -0.813
1722   Point 863       dX   1.647
1724   Point 864       dX  -0.801

[863 rows x 3 columns]

In [4]:
dy_data_array = load_step_191_data_frame.iloc[1::2]
dy_data_array

Element Property  Actual
1        Point 2       dY  -5.978
3        Point 3       dY  -6.090
5        Point 4       dY  -6.204
7        Point 5       dY  -6.325
9        Point 6       dY  -6.493
...          ...      ...     ...
1717   Point 860       dY  -9.345
1719   Point 861       dY  -9.449
1721   Point 862       dY  -9.534
1723   Point 863       dY  -5.866
1725   Point 864       dY  -9.623

[863 rows x 3 columns]

In [5]:
load_step_191 = pd.read_csv('C:/Users/fahad/OneDrive/Documents/GOM Results/Load 191 KN.csv',sep = ',',header = 0,
                            usecols = [4]) #[0,2,4]
load_step_191

Actual
0      1.651
1     -5.978
2      1.653
3     -6.090
4      1.651
...      ...
1721  -9.534
1722   1.647
1723  -5.866
1724  -0.801
1725  -9.623

[1726 rows x 1 columns]

In [6]:
dx = load_step_191.iloc[::2]
dx_num = dx.to_numpy()
#dx_num

In [7]:
dy = load_step_191.iloc[1::2]
dy_num = dy.to_numpy()
#dy_num

In [8]:
d_array = np.array([dx_num, dy_num])
d_array_transpose = d_array.T
d_array_transpose

array([[[ 1.651, -5.978],
        [ 1.653, -6.09 ],
        [ 1.651, -6.204],
        ...,
        [-0.813, -9.534],
        [ 1.647, -5.866],
        [-0.801, -9.623]]])

In [9]:
import glob
import pandas as pd

glued_data = pd.DataFrame()
for file_name in glob.glob('C:/Users/fahad/OneDrive/Documents/GOM Results/*.csv'):
    x = pd.read_csv(file_name, low_memory=False)
    glued_data = pd.concat([glued_data,x],axis=0)
glued_data

Element  Datum Property  Nominal  Actual  Tol -  Tol +    Dev  Check  \
0        Point 2    NaN       dX        0   0.000    NaN    NaN  0.000    NaN   
1        Point 2    NaN       dY        0   0.000    NaN    NaN  0.000    NaN   
2        Point 3    NaN       dX        0   0.000    NaN    NaN  0.000    NaN   
3        Point 3    NaN       dY        0   0.000    NaN    NaN  0.000    NaN   
4        Point 4    NaN       dX        0   0.000    NaN    NaN  0.000    NaN   
...          ...    ...      ...      ...     ...    ...    ...    ...    ...   
1721   Point 862    NaN       dY        0  -9.534    NaN    NaN -9.534    NaN   
1722   Point 863    NaN       dX        0   1.647    NaN    NaN  1.647    NaN   
1723   Point 863    NaN       dY        0  -5.866    NaN    NaN -5.866    NaN   
1724   Point 864    NaN       dX        0  -0.801    NaN    NaN -0.801    NaN   
1725   Point 864    NaN       dY        0  -9.623    NaN    NaN -9.623    NaN   

      Out  
0     NaN  
1     NaN  
2     NaN  
3     NaN  
4     NaN  
...   ...  
1721  NaN  
1722  NaN  
1723  NaN  
1724  NaN  
1725  NaN  

[8630 rows x 10 columns]

In [10]:
# import necessary libraries
import pandas as pd
import os
import glob
  
  
# use glob to get all the csv files 
# in the folder
path = os.getcwd()
csv_files = glob.glob(os.path.join(path, "C:/Users/fahad/OneDrive/Documents/GOM Results/*.csv"))
  
  
# loop over the list of csv files
for f in csv_files:
      
    # read the csv file
    df = pd.read_csv(f)
      
    # print the location and filename
    print('Location:', f)
    print('File Name:', f.split("\\")[-1])
      
    # print the content
    print('Content:')
    display(df)
    print()

Location: C:/Users/fahad/OneDrive/Documents/GOM Results\Load 0 KN.csv
File Name: Load 0 KN.csv
Content:


Element  Datum Property  Nominal  Actual  Tol -  Tol +  Dev  Check  \
0        Point 2    NaN       dX        0       0    NaN    NaN    0    NaN   
1        Point 2    NaN       dY        0       0    NaN    NaN    0    NaN   
2        Point 3    NaN       dX        0       0    NaN    NaN    0    NaN   
3        Point 3    NaN       dY        0       0    NaN    NaN    0    NaN   
4        Point 4    NaN       dX        0       0    NaN    NaN    0    NaN   
...          ...    ...      ...      ...     ...    ...    ...  ...    ...   
1721   Point 862    NaN       dY        0       0    NaN    NaN    0    NaN   
1722   Point 863    NaN       dX        0       0    NaN    NaN    0    NaN   
1723   Point 863    NaN       dY        0       0    NaN    NaN    0    NaN   
1724   Point 864    NaN       dX        0       0    NaN    NaN    0    NaN   
1725   Point 864    NaN       dY        0       0    NaN    NaN    0    NaN   

      Out  
0     NaN  
1     NaN  
2     NaN  
3     NaN  
4     NaN  
...   ...  
1721  NaN  
1722  NaN  
1723  NaN  
1724  NaN  
1725  NaN  

[1726 rows x 10 columns]


Location: C:/Users/fahad/OneDrive/Documents/GOM Results\Load 050 KN.csv
File Name: Load 050 KN.csv
Content:


Element  Datum Property  Nominal  Actual  Tol -  Tol +    Dev  Check  \
0        Point 2    NaN       dX        0   0.743    NaN    NaN  0.743    NaN   
1        Point 2    NaN       dY        0  -1.237    NaN    NaN -1.237    NaN   
2        Point 3    NaN       dX        0   0.742    NaN    NaN  0.742    NaN   
3        Point 3    NaN       dY        0  -1.251    NaN    NaN -1.251    NaN   
4        Point 4    NaN       dX        0   0.745    NaN    NaN  0.745    NaN   
...          ...    ...      ...      ...     ...    ...    ...    ...    ...   
1721   Point 862    NaN       dY        0  -1.747    NaN    NaN -1.747    NaN   
1722   Point 863    NaN       dX        0   0.738    NaN    NaN  0.738    NaN   
1723   Point 863    NaN       dY        0  -1.218    NaN    NaN -1.218    NaN   
1724   Point 864    NaN       dX        0   0.418    NaN    NaN  0.418    NaN   
1725   Point 864    NaN       dY        0  -1.759    NaN    NaN -1.759    NaN   

      Out  
0     NaN  
1     NaN  
2     NaN  
3     NaN  
4     NaN  
...   ...  
1721  NaN  
1722  NaN  
1723  NaN  
1724  NaN  
1725  NaN  

[1726 rows x 10 columns]


Location: C:/Users/fahad/OneDrive/Documents/GOM Results\Load 103 KN.csv
File Name: Load 103 KN.csv
Content:


Element  Datum Property  Nominal  Actual  Tol -  Tol +    Dev  Check  \
0        Point 2    NaN       dX        0   1.229    NaN    NaN  1.229    NaN   
1        Point 2    NaN       dY        0  -2.994    NaN    NaN -2.994    NaN   
2        Point 3    NaN       dX        0   1.223    NaN    NaN  1.223    NaN   
3        Point 3    NaN       dY        0  -3.042    NaN    NaN -3.042    NaN   
4        Point 4    NaN       dX        0   1.224    NaN    NaN  1.224    NaN   
...          ...    ...      ...      ...     ...    ...    ...    ...    ...   
1721   Point 862    NaN       dY        0  -4.473    NaN    NaN -4.473    NaN   
1722   Point 863    NaN       dX        0   1.225    NaN    NaN  1.225    NaN   
1723   Point 863    NaN       dY        0  -2.936    NaN    NaN -2.936    NaN   
1724   Point 864    NaN       dX        0   0.171    NaN    NaN  0.171    NaN   
1725   Point 864    NaN       dY        0  -4.505    NaN    NaN -4.505    NaN   

      Out  
0     NaN  
1     NaN  
2     NaN  
3     NaN  
4     NaN  
...   ...  
1721  NaN  
1722  NaN  
1723  NaN  
1724  NaN  
1725  NaN  

[1726 rows x 10 columns]


Location: C:/Users/fahad/OneDrive/Documents/GOM Results\Load 150 KN.csv
File Name: Load 150 KN.csv
Content:


Element  Datum Property  Nominal  Actual  Tol -  Tol +    Dev  Check  \
0        Point 2    NaN       dX        0   1.434    NaN    NaN  1.434    NaN   
1        Point 2    NaN       dY        0  -4.517    NaN    NaN -4.517    NaN   
2        Point 3    NaN       dX        0   1.436    NaN    NaN  1.436    NaN   
3        Point 3    NaN       dY        0  -4.600    NaN    NaN -4.600    NaN   
4        Point 4    NaN       dX        0   1.438    NaN    NaN  1.438    NaN   
...          ...    ...      ...      ...     ...    ...    ...    ...    ...   
1721   Point 862    NaN       dY        0  -6.912    NaN    NaN -6.912    NaN   
1722   Point 863    NaN       dX        0   1.436    NaN    NaN  1.436    NaN   
1723   Point 863    NaN       dY        0  -4.436    NaN    NaN -4.436    NaN   
1724   Point 864    NaN       dX        0  -0.280    NaN    NaN -0.280    NaN   
1725   Point 864    NaN       dY        0  -6.958    NaN    NaN -6.958    NaN   

      Out  
0     NaN  
1     NaN  
2     NaN  
3     NaN  
4     NaN  
...   ...  
1721  NaN  
1722  NaN  
1723  NaN  
1724  NaN  
1725  NaN  

[1726 rows x 10 columns]


Location: C:/Users/fahad/OneDrive/Documents/GOM Results\Load 191 KN.csv
File Name: Load 191 KN.csv
Content:


Element  Datum Property  Nominal  Actual  Tol -  Tol +    Dev  Check  \
0        Point 2    NaN       dX        0   1.651    NaN    NaN  1.651    NaN   
1        Point 2    NaN       dY        0  -5.978    NaN    NaN -5.978    NaN   
2        Point 3    NaN       dX        0   1.653    NaN    NaN  1.653    NaN   
3        Point 3    NaN       dY        0  -6.090    NaN    NaN -6.090    NaN   
4        Point 4    NaN       dX        0   1.651    NaN    NaN  1.651    NaN   
...          ...    ...      ...      ...     ...    ...    ...    ...    ...   
1721   Point 862    NaN       dY        0  -9.534    NaN    NaN -9.534    NaN   
1722   Point 863    NaN       dX        0   1.647    NaN    NaN  1.647    NaN   
1723   Point 863    NaN       dY        0  -5.866    NaN    NaN -5.866    NaN   
1724   Point 864    NaN       dX        0  -0.801    NaN    NaN -0.801    NaN   
1725   Point 864    NaN       dY        0  -9.623    NaN    NaN -9.623    NaN   

      Out  
0     NaN  
1     NaN  
2     NaN  
3     NaN  
4     NaN  
...   ...  
1721  NaN  
1722  NaN  
1723  NaN  
1724  NaN  
1725  NaN  

[1726 rows x 10 columns]

In [11]:
# arr = np.zeros()
# a1 = np.array([[1, 2], [3, 4]])
# b1 = np.array([[5, 6], [7, 8]])
# np.vstack((a1,b1))

In [12]:
import pandas as pd
import os
import glob
  
  
'use glob to get all the csv files' 
path = os.getcwd()
csv_files = glob.glob(os.path.join(path, "C:/Users/fahad/OneDrive/Documents/GOM Results/*.csv"))

csv_files_num = len(csv_files)
displacement_3d_array = None
# looping over list of csv files
for f in csv_files:
    
    # reading csv file and converting into an array
    df = pd.read_csv(f)
    dx = df.iloc[::2]
    dx_num = dx.to_numpy()
    dy = df.iloc[1::2]
    dy_num = dy.to_numpy()
    d_array = np.array([dx_num, dy_num])
    d_array_transpose = d_array.T[4] 
    
    # printing location of file and filename
    print('Location:', f)
    print('File Name:', f.split("\\")[-1])

    # printing values
    print('Displacements:')
    display(d_array_transpose)
    if displacement_3d_array is None:
        displacement_3d_array = d_array_transpose
    else:
        displacement_3d_array = np.vstack((displacement_3d_array, d_array_transpose))
    
    print()
print(displacement_3d_array)

Location: C:/Users/fahad/OneDrive/Documents/GOM Results\Load 0 KN.csv
File Name: Load 0 KN.csv
Displacements:


array([[0, 0],
       [0, 0],
       [0, 0],
       ...,
       [0, 0],
       [0, 0],
       [0, 0]], dtype=object)


Location: C:/Users/fahad/OneDrive/Documents/GOM Results\Load 050 KN.csv
File Name: Load 050 KN.csv
Displacements:


array([[0.743, -1.237],
       [0.742, -1.251],
       [0.745, -1.266],
       ...,
       [0.417, -1.747],
       [0.738, -1.218],
       [0.418, -1.759]], dtype=object)


Location: C:/Users/fahad/OneDrive/Documents/GOM Results\Load 103 KN.csv
File Name: Load 103 KN.csv
Displacements:


array([[1.229, -2.994],
       [1.223, -3.042],
       [1.224, -3.096],
       ...,
       [0.17, -4.473],
       [1.225, -2.936],
       [0.171, -4.505]], dtype=object)


Location: C:/Users/fahad/OneDrive/Documents/GOM Results\Load 150 KN.csv
File Name: Load 150 KN.csv
Displacements:


array([[1.434, -4.517],
       [1.436, -4.6],
       [1.438, -4.684],
       ...,
       [-0.275, -6.912],
       [1.436, -4.436],
       [-0.28, -6.958]], dtype=object)


Location: C:/Users/fahad/OneDrive/Documents/GOM Results\Load 191 KN.csv
File Name: Load 191 KN.csv
Displacements:


array([[1.651, -5.978],
       [1.653, -6.09],
       [1.651, -6.204],
       ...,
       [-0.813, -9.534],
       [1.647, -5.866],
       [-0.801, -9.623]], dtype=object)


[[0 0]
 [0 0]
 [0 0]
 ...
 [-0.813 -9.534]
 [1.647 -5.866]
 [-0.801 -9.623]]


In [13]:
displacement_3d_array

array([[0, 0],
       [0, 0],
       [0, 0],
       ...,
       [-0.813, -9.534],
       [1.647, -5.866],
       [-0.801, -9.623]], dtype=object)