# Current to do's 2022-28

- naming of coordinates - x horizontal, y vertical - encapsulate the differences in dic_grid, so that any further level works 
   without swapping
 - extend interpolation in dsf to cdf - including the time index - this will allow for the crack detection and spline representation    of the functions 
$$
\omega_C( t, y )
$$
 - use this function to determine
$$
y^\mathrm{tip}_C( t )
$$ 
$$
\Delta u_{Ca}( y, t ) = u( x+r, y, t ) - u( x-r, y, t ) 
$$
 - distinguish the change events - finer resolution of the tag types (TIME, ALG, MESH).

# Crack detection strategy

The detection algorithm uses the knowledge about shear crack propagation 
 - distance between cracks is related to the shielded length given by the reinforcement ratio      and bond properties
 - cracks start from the bottom of the cross section
 - cracks propagate upwards and bend in the direction of an increasing cross-sectional moment
 
The crack pattern in the shear zone gets most visible prior shortly before the maximum load has been reached. Near to the failure, the regularity of the crack pattern is lost and the specimen cannot be viewed as a series of individual shear cracks any more. The initiation of failure via a horizontal crossing crack initiated by a vertical stress component is initiated either near the reinforcement layer due to the dowel action or by a crack tip propagating horizontally through a compression zone.

## Full crack detection strategy

This observation is exploited by the crack detection algorithm by adapting the following strategy. 

 - The displacement field $U_{IJa}^{F_\gamma}$ corresponding to $F_\gamma = 0.9 F_\max$ is taken first to calculate the strain, damage and stress fields.
 - The DIC-FE state fields are interpolated and smoothed as a basis for the crack detection step. The crack detection algorithm is employed to detect the crack path $\mathcal{C}(F_\gamma)$ at the near-failure level of load. The algorithm delivers the crack tip positions.
 - The obtained crack path is then refined by analyzing the cracking process in reverse order $F = [F_\gamma, 0]$. The difference between damage fields $\omega_{MN}(F_\gamma)$ and $\omega_{MN}(F), n = [0, n_C-1]$  obtained using DIC-FE-MDM calculation for each $U_{IJa}$ state are analyzed to refine the crack geometry in the previous states of loading. After that, the load range between the crack detection state and the ultimate load is analyzed based on the known cracking state at the level $F\tilde{}$.
 - Define a spline function representing the damage along the crack
 
## Current strategy

The crack detection load level $\gamma$ is used to identify the primary cracks. The cracks that develop at the level $\gamma = 0.9$ up to the 0.4 of the cross sectional height are recognized as primary cracks. Partially, secondary cracks and noise in DIC data and FE approximation are avoided  by smoothing the damage field within a radius that reflects the element resolution / characteristic length? Currently, the primary cracks are identified first to obtain the crack zones.

# Stress profile evaluation

 - M, N, Q - evaluated from the constitutive laws along the ligament
 - Crack-tip stress / strain / opening. 
 - How to include the history of damage into the stress evaluation (softening law)

 - Add the 

In [1]:
%matplotlib widget
import ibvpy.api as ib
import matplotlib.pylab as plt
from matplotlib import cm
from scipy.interpolate import interp2d
from scipy.signal import argrelextrema
from bmcs_shear.api import CrackBridgeAdv
from bmcs_shear.dic_crack import\
    DICGrid, DICStateFields, DICCrackList, DICCrack, DICCrackCOR
from bmcs_shear.shear_crack.crack_path import get_T_Lab
import numpy as np
np.seterr(divide='ignore', invalid='ignore');

In [2]:
dic_grid = DICGrid(U_factor=100, dir_name='B10_TV2')

In [3]:
dsf = DICStateFields(dic_grid=dic_grid, t=0.9)
dsf.tmodel_.trait_set(E=5000, c_T=0, nu=0.18, epsilon_0=0.0005, epsilon_f=0.01);
dsf.eval()

In [4]:
dcl = DICCrackList(dsf=dsf, eta=1)

In [5]:
dcl.interact()

In [6]:
self = dcl.items[1].sp
self.F_a

array([164001.35017621,  16800.45788327])

In [7]:
y_neutral = self.X_neutral_a[1]
S_La = self.S_La
irange = np.where(self.X_La[:, 1] < y_neutral)[0][::-1]
S_ = np.hstack([[0], S_La[irange, 0]])
y_ = np.hstack([[y_neutral], self.X_La[irange, 1]]) - y_neutral
self.X_La[irange, 1], self.dic_crack.X_Ka[:, 1], irange

(array([233.97980465, 225.71754377, 217.45528289, 209.19302201,
        200.93076113, 200.20537932, 195.35442872, 190.50347812,
        185.65252752, 180.80157692, 175.95062632, 171.09967572,
        166.24872512, 161.39777452, 156.54682392, 151.69587332,
        146.84492272, 141.99397212, 137.14302152, 132.29207092,
        127.44112032, 122.59016972, 117.73921912, 112.88826852,
        108.03731792, 103.18636732,  98.33541672,  93.48446612,
         88.63351552,  83.78256492,  78.93161432,  74.08066372,
         69.22971312,  64.37876252,  59.52781192,  54.67686132,
         49.82591072,  44.97496012,  40.12400952,  35.27305892,
         30.42210832]),
 array([ 30.42210832,  35.27305892,  40.12400952,  44.97496012,
         49.82591072,  54.67686132,  59.52781192,  64.37876252,
         69.22971312,  74.08066372,  78.93161432,  83.78256492,
         88.63351552,  93.48446612,  98.33541672, 103.18636732,
        108.03731792, 112.88826852, 117.73921912, 122.59016972,
        127.4411

In [8]:
y_

array([   0.        ,   -7.90310377,  -16.16536464,  -24.42762552,
        -32.6898864 ,  -40.95214728,  -41.67752909,  -46.52847969,
        -51.37943029,  -56.23038089,  -61.08133149,  -65.93228209,
        -70.78323269,  -75.63418329,  -80.48513389,  -85.33608449,
        -90.18703509,  -95.03798569,  -99.88893629, -104.73988689,
       -109.59083749, -114.44178809, -119.29273869, -124.14368929,
       -128.99463989, -133.84559049, -138.69654109, -143.54749169,
       -148.39844229, -153.24939289, -158.10034349, -162.95129409,
       -167.80224469, -172.65319529, -177.50414589, -182.35509649,
       -187.20604709, -192.05699769, -196.90794829, -201.75889889,
       -206.60984949, -211.46080009])

In [9]:
get_S, get_Y = self.get_SY
y_L = get_Y(S_[:-1], S_[1:], y_[:-1], y_[1:])
S_L = get_S(S_[:-1], S_[1:], y_[:-1], y_[1:])
y_[1:]-y_[:-1]

array([-7.90310377, -8.26226088, -8.26226088, -8.26226088, -8.26226088,
       -0.72538181, -4.8509506 , -4.8509506 , -4.8509506 , -4.8509506 ,
       -4.8509506 , -4.8509506 , -4.8509506 , -4.8509506 , -4.8509506 ,
       -4.8509506 , -4.8509506 , -4.8509506 , -4.8509506 , -4.8509506 ,
       -4.8509506 , -4.8509506 , -4.8509506 , -4.8509506 , -4.8509506 ,
       -4.8509506 , -4.8509506 , -4.8509506 , -4.8509506 , -4.8509506 ,
       -4.8509506 , -4.8509506 , -4.8509506 , -4.8509506 , -4.8509506 ,
       -4.8509506 , -4.8509506 , -4.8509506 , -4.8509506 , -4.8509506 ,
       -4.8509506 ])

In [10]:
sum_S = np.sum(S_L)
sum_Sy = np.sum(S_L * y_L)
cg_y = sum_Sy / sum_S
-sum_S * self.bd.B, cg_y + y_neutral

(158364.5338596102, 170.70999935973254)

In [11]:
self.interact()

In [47]:
a_M = np.arange(3)
b_N = np.arange(3, 3+4)
c_T = np.arange(3+4, 3+4+5)
a_MN, b_MN = np.meshgrid(a_M, b_N, indexing='ij')
c_TMN, a_TMN, b_TMN = np.meshgrid(c_T, a_M, b_N, indexing='ij')
C_TMN, A_TMN, B_TMN = np.broadcast_arrays(c_T[:, np.newaxis, np.newaxis],
                                          a_MN[np.newaxis, :, :], 
                                          b_MN[np.newaxis, :, :], 
                                          )
np.sum(b_TMN - B_TMN)

0

## Reverse crack detection 

 * Get the crack detection field and the primary cracks
   detected at the state of the mature cracking stage, 
   i.e. near the ultimate load.

### How to access the values of crack detection field at the crack tip

In [18]:
def get_crack_t(eta = 0.95):
    '''Get the crack history starting with the critical
    '''
    # identify the near feilure crack pattern
    t_eta_idx = dcl.dsf.dic_grid.get_F_eta_dic_idx(eta)
    dcl.dsf.dic_grid.end_t = t_eta_idx
    xx_NC, yy_NC, N_tip_C, M_NC = dcl.primary_cracks
    # pripare the list of crack tip states as a funciton of t
    N_tip_Ct = np.zeros((len(N_tip_C), t_eta_idx+1), np.int_)
    M_tip_Ct = np.zeros_like(N_tip_Ct)
    print('t_idx: ', end='')
    for t_idx in range(t_eta_idx, -1, -1):
        N_tip_C = np.copy(N_tip_C)
        N_tip_Ct[:, t_idx] = np.copy(N_tip_C)
        M_tip_Ct[:, t_idx] = M_NC[N_tip_C, np.arange(len(N_tip_C))]
        print(t_idx, end=' ')
        # get the crack detection field for the current time index
        dcl.dsf.dic_grid.end_t = t_idx
        _, _, cdf_MN = dcl.dsf.crack_detection_field
        # for each crack get the indexes starting from the current tip
        N_tip_CN = [np.arange(N_tip, -1, -1) for N_tip in N_tip_C]
        M_tip_CN = [M_NC[N_tip_t, C] for C, N_tip_t in enumerate(N_tip_CN)]
        # evaluate crack detection field along each crack
        cdf_CN = [cdf_MN[M_tip_N, N_tip_N] 
                  for M_tip_N, N_tip_N in zip(M_tip_CN, N_tip_CN)]
        # if cdf is zero completely - the crack did not emerge yet
        cdf_nonzero_C = np.array([np.sum(cdf_N) for cdf_N in cdf_CN]) > 0
        # find the row index distance from the tip with damage larger 
        # than threshold
        dN_C = np.array([np.argmax(cdf_C >= 0.2) for cdf_C in cdf_CN])
        N_tip_C[cdf_nonzero_C] -= dN_C[cdf_nonzero_C]
        N_tip_C[np.logical_not(cdf_nonzero_C)] = 0
    return M_tip_Ct, N_tip_Ct

In [19]:
get_crack_t()

t_idx: 18 17 16 15 14 13 12 11 10 9 8 7 6 5 4 3 2 1 0 

(array([[ 9,  9,  9,  9,  9, 10, 10, 10, 10,  9,  9,  8,  7,  6,  6,  6,
          6,  6,  6],
        [17, 17, 16, 16, 15, 14, 14, 13, 13, 13, 13, 13, 13, 13, 13, 13,
         13, 13, 13],
        [29, 29, 29, 29, 29, 28, 28, 27, 27, 27, 27, 27, 27, 27, 26, 26,
         26, 26, 26],
        [43, 43, 43, 42, 41, 40, 40, 40, 39, 39, 39, 39, 38, 38, 38, 38,
         38, 38, 38],
        [62, 62, 62, 62, 61, 60, 60, 60, 60, 60, 59, 58, 57, 56, 56, 56,
         56, 56, 56],
        [76, 76, 76, 76, 76, 76, 76, 76, 75, 74, 74, 74, 74, 74, 74, 74,
         74, 74, 74],
        [94, 94, 94, 94, 94, 94, 94, 94, 94, 94, 94, 95, 95, 95, 94, 92,
         92, 92, 92]]),
 array([[ 0,  0,  0,  0,  0,  2,  5,  7,  7,  9,  9, 14, 16, 18, 19, 19,
         19, 19, 19],
        [ 0,  0,  5, 11, 15, 16, 17, 18, 18, 18, 18, 18, 18, 18, 18, 18,
         18, 18, 18],
        [ 0,  0,  0,  1,  7,  9,  9, 12, 12, 15, 15, 16, 16, 16, 17, 17,
         17, 17, 17],
        [ 0,  0,  0,  8, 12, 15, 15, 15, 16, 16,

In [8]:
dcl.cracks_t

t_idx: 18 17 16 15 14 13 12 11 10 9 8 7 6 5 4 3 2 1 0 

([array([ 6, 13, 26, 38, 56, 74, 92]),
  array([ 6, 13, 26, 38, 56, 74, 92]),
  array([ 6, 13, 26, 38, 56, 74, 92]),
  array([ 6, 13, 26, 38, 56, 74, 92]),
  array([ 6, 13, 26, 38, 56, 74, 94]),
  array([ 6, 13, 27, 38, 56, 74, 95]),
  array([ 7, 13, 27, 38, 57, 74, 95]),
  array([ 8, 13, 27, 39, 58, 74, 95]),
  array([ 9, 13, 27, 39, 59, 74, 95]),
  array([ 9, 13, 27, 39, 60, 74, 95]),
  array([10, 13, 27, 39, 60, 75, 95]),
  array([10, 13, 27, 40, 60, 76, 95]),
  array([10, 14, 28, 40, 60, 76, 95]),
  array([10, 14, 28, 40, 60, 76, 95]),
  array([10, 15, 29, 41, 61, 76, 95]),
  array([10, 16, 29, 42, 61, 76, 95]),
  array([10, 16, 29, 42, 61, 76, 95]),
  array([10, 16, 29, 42, 61, 76, 95]),
  array([10, 16, 29, 42, 61, 76, 95])],
 [array([19, 18, 17, 19, 19, 16, 10]),
  array([19, 18, 17, 19, 19, 16, 10]),
  array([19, 18, 17, 19, 19, 16, 10]),
  array([19, 18, 17, 19, 19, 16, 10]),
  array([19, 18, 17, 19, 19, 16,  8]),
  array([18, 18, 16, 19, 19, 16,  7]),
  array([16, 18, 16, 19,

In [40]:
_, _, cdf_eta_MN = dcl.dsf.crack_detection_field

(116, 28)

In [27]:
xx_NC, yy_NC, N_tip_C, M_NC = dcl.primary_cracks

In [28]:
N_tip_C

array([19, 18, 17, 19, 19, 16, 10])

In [29]:
M_tip_C = M_NC[N_tip_C,np.arange(len(N_tip_C))]

In [30]:
M_tip_C

array([ 6, 13, 26, 38, 56, 74, 92])

In [31]:
cdf_eta_MN[M_tip_C, N_tip_C]

array([0.24249924, 0.27093637, 0.22398292, 0.38911079, 0.23217991,
       0.24228758, 0.2987822 ])

In [35]:
dcl.dsf.dic_grid.end_t = t_eta_idx - 1

In [36]:
_, _, cdf_MN = dcl.dsf.crack_detection_field
cdf_MN.shape

(116, 28)

In [38]:
cdf_MN[M_tip_C, N_tip_C]

array([0.2102562 , 0.33028572, 0.22957975, 0.28097628, 0.31755808,
       0.30542646, 0.2718454 ])

### How to access the crack detection field for lower load levels

In [15]:
dcl.dsf.dic_grid.end_t

11

In [16]:
sp = dcl.items[3]

In [17]:
sp.X_neutral_a

array([423.21144987, 235.67818428])

In [18]:
x_00 = sp.dic_crack.C_cubic_spline(sp.z_N)

In [19]:
x_00

array([472.76657979])

In [20]:
sp.M

nan

In [11]:
dcl.interact()

In [12]:
crack_0 = dcl.items[2]

In [13]:
crack_0.pos_F_y

(nan, nan)

In [9]:
fig, ax = plt.subplots(1,1)
crack_0.dic_crack.plot_u_Nib(ax)
crack_0.dic_crack.plot_x_Na(ax)
crack_0.plot_COR(ax)
crack_0.plot_cor_markers(ax)
ax.axis('equal')

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

(248.36770344360858, 480.1367773488707, -7.550799748321647, 274.79547068760746)

In [ ]:
crack_0.M_N[20]

In [ ]:
dc_cor = DICCrackCOR(dic_crack=dcl.items[2])

In [ ]:
dc_cor.M_N.dtype

In [ ]:
slice_M_N = slice(dc_cor.M_N,dc_cor.M_N+3)

In [ ]:
X_mNa = np.array([dc_cor.X_MNa[dc_cor.M_N+i, np.arange(len(dc_cor.M_N))] for i in range(5)])

In [ ]:
X_mNa[-1,0]

In [ ]:
dc_cor.M0

In [ ]:
dc_cor.interact()

In [ ]:
dc_cor.X0_a - dc_cor.U0_a

In [19]:
dc_cor.x_ref_MNa_scaled[dc_cor.M0, :dc_cor.N0_max]

array([[330.87272231,   4.85905338],
       [330.87254552,  13.86303457],
       [330.87358701,  22.868741  ],
       [330.87234085,  31.88218863],
       [330.87220829,  40.89703656]])