# Current to do's 2022-28

- naming of coordinates - x horizontal, y vertical - encapsulate the differences in dic_grid, so that any further level works 
   without swapping
 - extend interpolation in dsf to cdf - including the time index - this will allow for the crack detection and spline representation    of the functions 
$$
\omega_C( t, y )
$$
 - use this function to determine
$$
y^\mathrm{tip}_C( t )
$$ 
$$
\Delta u_{Ca}( y, t ) = u( x+r, y, t ) - u( x-r, y, t ) 
$$
 - Constitutive laws applied across the crack ligament
$$
 \sigma_{Cab}(y, t) = \mathcal{S}_{ab}(\Delta u{Ca}(y, t))
$$
 - distinguish the change events - finer resolution of the tag types (TIME, ALG, MESH).

# Crack detection strategy

The detection algorithm uses the knowledge about shear crack propagation 
 - distance between cracks is related to the shielded length given by the reinforcement ratio      and bond properties
 - cracks start from the bottom of the cross section
 - cracks propagate upwards and bend in the direction of an increasing cross-sectional moment
 
The crack pattern in the shear zone gets most visible prior shortly before the maximum load has been reached. Near to the failure, the regularity of the crack pattern is lost and the specimen cannot be viewed as a series of individual shear cracks any more. The initiation of failure via a horizontal crossing crack initiated by a vertical stress component is initiated either near the reinforcement layer due to the dowel action or by a crack tip propagating horizontally through a compression zone.

## Full crack detection strategy

This observation is exploited by the crack detection algorithm by adapting the following strategy. 

 - The displacement field $U_{IJa}^{F_\gamma}$ corresponding to $F_\gamma = 0.9 F_\max$ is taken first to calculate the strain, damage and stress fields.
 - The DIC-FE state fields are interpolated and smoothed as a basis for the crack detection step. The crack detection algorithm is employed to detect the crack path $\mathcal{C}(F_\gamma)$ at the near-failure level of load. The algorithm delivers the crack tip positions.
 - The obtained crack path is then refined by analyzing the cracking process in reverse order $F = [F_\gamma, 0]$. The difference between damage fields $\omega_{MN}(F_\gamma)$ and $\omega_{MN}(F), n = [0, n_C-1]$  obtained using DIC-FE-MDM calculation for each $U_{IJa}$ state are analyzed to refine the crack geometry in the previous states of loading. After that, the load range between the crack detection state and the ultimate load is analyzed based on the known cracking state at the level $F\tilde{}$.
 - Define a spline function representing the damage along the crack
 
## Current strategy

The crack detection load level $\gamma$ is used to identify the primary cracks. The cracks that develop at the level $\gamma = 0.9$ up to the 0.4 of the cross sectional height are recognized as primary cracks. Partially, secondary cracks and noise in DIC data and FE approximation are avoided  by smoothing the damage field within a radius that reflects the element resolution / characteristic length? Currently, the primary cracks are identified first to obtain the crack zones.

# Stress profile evaluation

 - M, N, Q - evaluated from the constitutive laws along the ligament
 - Crack-tip stress / strain / opening. 
 - How to include the history of damage into the stress evaluation (softening law)


## Constitutive laws along the ligament

The transition between strain concentration and discrete crack representation is based on the threshold value of the critical strain $\varepsilon_\mathrm{cr}$. This value corresponds to the strain with the onset of softening, i.e.
$$
 \varepsilon_\mathrm{cr} = \mathrm{argmax}_\varepsilon \mathcal{S}(\varepsilon).
$$
In case of a linear ascending branch, this relation is obtained as
$$
 \varepsilon_\mathrm{cr} = \frac{ f_\mathrm{t} }{ E }
$$

The stress in the ascending range is controlled by strain 
$$
\sigma_a
  = \left\{  
 \begin{array}{l}
 \mathcal{S}(\varepsilon)\; \mathrm{if} \; \varepsilon < \varepsilon_\mathrm{cr}
 \\
 \mathcal{S}(w) \; \mathrm{otherwise}
 \end{array}
 \right.
$$

An alternative approach is to introduce an equivalent strain or yield function.

# Todo

 - Add the extrapolation to include the top layer of the cross section [Done]
 - Separate the constitutive law for compression and tension
 - Include compression law considering the 3D stress state (plain stress)
 - In stress and force plot - align the ligament axis and show the capacity value for the reinforcement to indicate that it is yielding
 - bmcs_utils - improve the dependency management so that the tree nodes are not needed everywhere

In [1]:
%matplotlib widget
import ibvpy.api as ib
import matplotlib.pylab as plt
from matplotlib import cm
from scipy.interpolate import interp2d
from scipy.signal import argrelextrema
from bmcs_shear.api import CrackBridgeAdv
from bmcs_shear.dic_crack import\
    DICGrid, DICStateFields, DICCrackList, DICCrack, DICCrackCOR
from bmcs_shear.shear_crack.crack_path import get_T_Lab
import numpy as np
np.seterr(divide='ignore', invalid='ignore');

In [2]:
dic_grid = DICGrid(U_factor=100, dir_name='B7_TV1', t=0.1)
dic_grid.interact()

In [3]:
l_cb = dic_grid.d_x * 1

In [45]:
dsf = DICStateFields(dic_grid=dic_grid)
dsf.tmodel_.trait_set(E=5000, c_T=0, nu=0.18, epsilon_0=0.0005, epsilon_f=0.02/l_cb, eps_max=0.005);
dsf.tmodel_.G_f * dic_grid.d_x

0.07805377028082207

In [46]:
dsf.tmodel_.interact()

In [47]:
dsf.eval()
dsf.dic_grid.sz_bd.matrix_.L_cr = 30

In [48]:
dic_grid.X_frame

(12.0, 21.0, 1266.0, 307.0)

In [49]:
dsf.X_MNa[0,0]

array([16.64914704, 25.64914704])

In [50]:
dsf.interact()

In [51]:
self = dsf
cd_field_MN = self.omega_MN
X_MNa = self.X_MNa
X_aMN = np.einsum('MNa->aMN', X_MNa)
x_MN, y_MN = X_aMN
xx_NM, yy_NM, cd_field_ipl_NM = self.interp_omega(x_MN, y_MN, cd_field_MN)

In [52]:
x_MN[0,0], xx_NM[0,0]

(16.649147038914116, 16.649147038914116)

In [53]:
dcl = DICCrackList(dsf=dsf, eta=1)

Creating cracks


In [54]:
xx_MN, yy_MN, cd_field_irn_MN = dcl.dsf.crack_detection_field

In [55]:
xx_MN[0, 0]

16.649147038914116

In [56]:
# dcl.interact()

In [57]:
dcl.items[1].sp.smeared_matmod.interact()

In [58]:
cl1 = dcl.items[1]

In [59]:
cl1.n_K_ligament

100

In [60]:
cl1.sp.pos_F_y

(103607.93812494524, 211.8515952142309)

In [61]:
cl1.interact()

In [62]:
X_Ka, T_Kab, X_unc_Ka, X_crc_Ka, T_Kab = cl1.get_crack_ligament([100, 100])

In [63]:
self = dsf
n_dic_T = self.dic_grid.n_dic_T
dic_T = np.arange(n_dic_T)
X_IJa = self.dic_grid.X_IJa
U_TIJa = self.dic_grid.U_TIJa[:n_dic_T, ...]
x_IJ, y_IJ = np.einsum('IJa->aIJ', X_IJa)
dic_t = dic_T / (self.dic_grid.n_dic_T - 1)
txy = (dic_t, x_IJ[:, 0], y_IJ[0, :])
np.min(y_IJ)

21.0

In [64]:
self = cl1
X_Ka = self.X_crc_Ka
t = 0.5
np.min(X_Ka[:, 1])

25.649147038914112

In [23]:

d_x = self.d_x / 2
x_K, y_K = X_Ka.T
t_K = np.ones_like(x_K) * t
tX_right_K = np.array([t_K, x_K + d_x, y_K], dtype=np.float_).T
tX_left_K = np.array([t_K, x_K - d_x, y_K], dtype=np.float_).T
U_Ka = self.cl.dsf.f_U_ipl_txy(tX_right_K) - self.cl.dsf.f_U_ipl_txy(tX_left_K)

In [24]:
U_Ka

array([[0.14718948, 0.20555995],
       [0.14486277, 0.20502422],
       [0.14516304, 0.2052499 ],
       [0.14778794, 0.20617777],
       [0.14757735, 0.20636411],
       [0.14568786, 0.20615376],
       [0.14393314, 0.20603711],
       [0.14238889, 0.20600979],
       [0.13846337, 0.20609011],
       [0.13153556, 0.20603089],
       [0.12369114, 0.20565118],
       [0.11436778, 0.20478578],
       [0.10870244, 0.20471085],
       [0.1164845 , 0.20822035],
       [0.12404568, 0.21139124],
       [0.13263227, 0.21490927],
       [0.14123069, 0.21859916],
       [0.13633036, 0.21760878],
       [0.13153846, 0.21675213],
       [0.12683718, 0.21604465],
       [0.12220329, 0.21547498],
       [0.1164491 , 0.21551   ],
       [0.11062572, 0.21559094],
       [0.1047845 , 0.21563444],
       [0.0989121 , 0.21555322],
       [0.09193969, 0.21244213],
       [0.08240014, 0.20732515],
       [0.07217367, 0.20182748],
       [0.0614428 , 0.19611146],
       [0.04985013, 0.19070607],
       [0.

In [25]:
cl1.U1_Ka

array([[ 4.79873682e-03,  1.19039393e-02],
       [ 5.44783436e-03,  1.17673113e-02],
       [ 6.02649747e-03,  1.15622098e-02],
       [ 6.54587757e-03,  1.13020805e-02],
       [ 6.51569176e-03,  1.14173595e-02],
       [ 6.31745445e-03,  1.17351471e-02],
       [ 6.13181932e-03,  1.21108094e-02],
       [ 5.95443516e-03,  1.25399065e-02],
       [ 5.37401526e-03,  1.28713969e-02],
       [ 4.54850578e-03,  1.31262273e-02],
       [ 3.75933221e-03,  1.34059770e-02],
       [ 3.02716379e-03,  1.37175189e-02],
       [ 2.41893420e-03,  1.39194892e-02],
       [ 1.83435718e-03,  1.38433388e-02],
       [ 1.12089397e-03,  1.36585951e-02],
       [ 3.21559992e-04,  1.33024578e-02],
       [-2.81020041e-04,  1.28491451e-02],
       [-3.67446328e-04,  1.24910610e-02],
       [-4.37159708e-04,  1.21307601e-02],
       [-4.87426664e-04,  1.17760626e-02],
       [-6.48491214e-04,  1.14889167e-02],
       [-1.30567528e-03,  1.14583789e-02],
       [-1.95839393e-03,  1.14583977e-02],
       [-2.

In [26]:
eps_cr = -dcl.dsf.dic_grid.sz_bd.matrix_.f_c / dcl.dsf.dic_grid.sz_bd.matrix_.E_c

In [27]:
dcl.items[1].U1_Kb[-1, 0]

0.0018713695580372274

In [ ]:
_, ax = plt.subplots(1,1)
eps = np.array([np.linspace(0, -0.002, 40),
                  np.linspace(0, -0.002, 40)]).T
ax.plot(eps[:,0], dcl.dsf.dic_grid.sz_bd.matrix_.get_sig_a(eps)[:,0])
ax.plot([eps_cr],[0],'o')

In [ ]:
dcl.dsf.dic_grid.sz_bd.matrix_.symb.sig_w

In [17]:
dcl.dsf.dic_grid.sz_bd.matrix_.get_sig_a(dcl.items[1].U1_Kb[-1, :])

IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

In [18]:
dcl.dsf.dic_grid.sz_bd.matrix_.get_sig_a(dcl.items[1].U1_Kb[-1, :])

IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

In [11]:
dcl.dsf.interact()

In [7]:
a_M = np.arange(3)
b_N = np.arange(3, 3+4)
c_T = np.arange(3+4, 3+4+5)
a_MN, b_MN = np.meshgrid(a_M, b_N, indexing='ij')
c_TMN, a_TMN, b_TMN = np.meshgrid(c_T, a_M, b_N, indexing='ij')
C_TMN, A_TMN, B_TMN = np.broadcast_arrays(c_T[:, np.newaxis, np.newaxis],
                                          a_MN[np.newaxis, :, :], 
                                          b_MN[np.newaxis, :, :], 
                                          )
np.sum(b_TMN - B_TMN)

0

## Reverse crack detection 

 * Get the crack detection field and the primary cracks
   detected at the state of the mature cracking stage, 
   i.e. near the ultimate load.

### How to access the values of crack detection field at the crack tip

In [18]:
def get_crack_t(eta = 0.95):
    '''Get the crack history starting with the critical
    '''
    # identify the near feilure crack pattern
    t_eta_idx = dcl.dsf.dic_grid.get_F_eta_dic_idx(eta)
    dcl.dsf.dic_grid.end_t = t_eta_idx
    xx_NC, yy_NC, N_tip_C, M_NC = dcl.primary_cracks
    # pripare the list of crack tip states as a funciton of t
    N_tip_Ct = np.zeros((len(N_tip_C), t_eta_idx+1), np.int_)
    M_tip_Ct = np.zeros_like(N_tip_Ct)
    print('t_idx: ', end='')
    for t_idx in range(t_eta_idx, -1, -1):
        N_tip_C = np.copy(N_tip_C)
        N_tip_Ct[:, t_idx] = np.copy(N_tip_C)
        M_tip_Ct[:, t_idx] = M_NC[N_tip_C, np.arange(len(N_tip_C))]
        print(t_idx, end=' ')
        # get the crack detection field for the current time index
        dcl.dsf.dic_grid.end_t = t_idx
        _, _, cdf_MN = dcl.dsf.crack_detection_field
        # for each crack get the indexes starting from the current tip
        N_tip_CN = [np.arange(N_tip, -1, -1) for N_tip in N_tip_C]
        M_tip_CN = [M_NC[N_tip_t, C] for C, N_tip_t in enumerate(N_tip_CN)]
        # evaluate crack detection field along each crack
        cdf_CN = [cdf_MN[M_tip_N, N_tip_N] 
                  for M_tip_N, N_tip_N in zip(M_tip_CN, N_tip_CN)]
        # if cdf is zero completely - the crack did not emerge yet
        cdf_nonzero_C = np.array([np.sum(cdf_N) for cdf_N in cdf_CN]) > 0
        # find the row index distance from the tip with damage larger 
        # than threshold
        dN_C = np.array([np.argmax(cdf_C >= 0.2) for cdf_C in cdf_CN])
        N_tip_C[cdf_nonzero_C] -= dN_C[cdf_nonzero_C]
        N_tip_C[np.logical_not(cdf_nonzero_C)] = 0
    return M_tip_Ct, N_tip_Ct

In [19]:
get_crack_t()

t_idx: 18 17 16 15 14 13 12 11 10 9 8 7 6 5 4 3 2 1 0 

(array([[ 9,  9,  9,  9,  9, 10, 10, 10, 10,  9,  9,  8,  7,  6,  6,  6,
          6,  6,  6],
        [17, 17, 16, 16, 15, 14, 14, 13, 13, 13, 13, 13, 13, 13, 13, 13,
         13, 13, 13],
        [29, 29, 29, 29, 29, 28, 28, 27, 27, 27, 27, 27, 27, 27, 26, 26,
         26, 26, 26],
        [43, 43, 43, 42, 41, 40, 40, 40, 39, 39, 39, 39, 38, 38, 38, 38,
         38, 38, 38],
        [62, 62, 62, 62, 61, 60, 60, 60, 60, 60, 59, 58, 57, 56, 56, 56,
         56, 56, 56],
        [76, 76, 76, 76, 76, 76, 76, 76, 75, 74, 74, 74, 74, 74, 74, 74,
         74, 74, 74],
        [94, 94, 94, 94, 94, 94, 94, 94, 94, 94, 94, 95, 95, 95, 94, 92,
         92, 92, 92]]),
 array([[ 0,  0,  0,  0,  0,  2,  5,  7,  7,  9,  9, 14, 16, 18, 19, 19,
         19, 19, 19],
        [ 0,  0,  5, 11, 15, 16, 17, 18, 18, 18, 18, 18, 18, 18, 18, 18,
         18, 18, 18],
        [ 0,  0,  0,  1,  7,  9,  9, 12, 12, 15, 15, 16, 16, 16, 17, 17,
         17, 17, 17],
        [ 0,  0,  0,  8, 12, 15, 15, 15, 16, 16,

In [8]:
dcl.cracks_t

t_idx: 18 17 16 15 14 13 12 11 10 9 8 7 6 5 4 3 2 1 0 

([array([ 6, 13, 26, 38, 56, 74, 92]),
  array([ 6, 13, 26, 38, 56, 74, 92]),
  array([ 6, 13, 26, 38, 56, 74, 92]),
  array([ 6, 13, 26, 38, 56, 74, 92]),
  array([ 6, 13, 26, 38, 56, 74, 94]),
  array([ 6, 13, 27, 38, 56, 74, 95]),
  array([ 7, 13, 27, 38, 57, 74, 95]),
  array([ 8, 13, 27, 39, 58, 74, 95]),
  array([ 9, 13, 27, 39, 59, 74, 95]),
  array([ 9, 13, 27, 39, 60, 74, 95]),
  array([10, 13, 27, 39, 60, 75, 95]),
  array([10, 13, 27, 40, 60, 76, 95]),
  array([10, 14, 28, 40, 60, 76, 95]),
  array([10, 14, 28, 40, 60, 76, 95]),
  array([10, 15, 29, 41, 61, 76, 95]),
  array([10, 16, 29, 42, 61, 76, 95]),
  array([10, 16, 29, 42, 61, 76, 95]),
  array([10, 16, 29, 42, 61, 76, 95]),
  array([10, 16, 29, 42, 61, 76, 95])],
 [array([19, 18, 17, 19, 19, 16, 10]),
  array([19, 18, 17, 19, 19, 16, 10]),
  array([19, 18, 17, 19, 19, 16, 10]),
  array([19, 18, 17, 19, 19, 16, 10]),
  array([19, 18, 17, 19, 19, 16,  8]),
  array([18, 18, 16, 19, 19, 16,  7]),
  array([16, 18, 16, 19,

In [40]:
_, _, cdf_eta_MN = dcl.dsf.crack_detection_field

(116, 28)

In [27]:
xx_NC, yy_NC, N_tip_C, M_NC = dcl.primary_cracks

In [28]:
N_tip_C

array([19, 18, 17, 19, 19, 16, 10])

In [29]:
M_tip_C = M_NC[N_tip_C,np.arange(len(N_tip_C))]

In [30]:
M_tip_C

array([ 6, 13, 26, 38, 56, 74, 92])

In [31]:
cdf_eta_MN[M_tip_C, N_tip_C]

array([0.24249924, 0.27093637, 0.22398292, 0.38911079, 0.23217991,
       0.24228758, 0.2987822 ])

In [35]:
dcl.dsf.dic_grid.end_t = t_eta_idx - 1

In [36]:
_, _, cdf_MN = dcl.dsf.crack_detection_field
cdf_MN.shape

(116, 28)

In [38]:
cdf_MN[M_tip_C, N_tip_C]

array([0.2102562 , 0.33028572, 0.22957975, 0.28097628, 0.31755808,
       0.30542646, 0.2718454 ])

### How to access the crack detection field for lower load levels

In [15]:
dcl.dsf.dic_grid.end_t

11

In [16]:
sp = dcl.items[3]

In [17]:
sp.X_neutral_a

array([423.21144987, 235.67818428])

In [18]:
x_00 = sp.dic_crack.C_cubic_spline(sp.z_N)

In [19]:
x_00

array([472.76657979])

In [20]:
sp.M

nan

In [11]:
dcl.interact()

In [12]:
crack_0 = dcl.items[2]

In [13]:
crack_0.pos_F_y

(nan, nan)

In [9]:
fig, ax = plt.subplots(1,1)
crack_0.dic_crack.plot_u_Nib(ax)
crack_0.dic_crack.plot_x_Na(ax)
crack_0.plot_COR(ax)
crack_0.plot_cor_markers(ax)
ax.axis('equal')

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

(248.36770344360858, 480.1367773488707, -7.550799748321647, 274.79547068760746)

In [ ]:
crack_0.M_N[20]

In [ ]:
dc_cor = DICCrackCOR(dic_crack=dcl.items[2])

In [ ]:
dc_cor.M_N.dtype

In [ ]:
slice_M_N = slice(dc_cor.M_N,dc_cor.M_N+3)

In [ ]:
X_mNa = np.array([dc_cor.X_MNa[dc_cor.M_N+i, np.arange(len(dc_cor.M_N))] for i in range(5)])

In [ ]:
X_mNa[-1,0]

In [ ]:
dc_cor.M0

In [ ]:
dc_cor.interact()

In [ ]:
dc_cor.X0_a - dc_cor.U0_a

In [19]:
dc_cor.x_ref_MNa_scaled[dc_cor.M0, :dc_cor.N0_max]

array([[330.87272231,   4.85905338],
       [330.87254552,  13.86303457],
       [330.87358701,  22.868741  ],
       [330.87234085,  31.88218863],
       [330.87220829,  40.89703656]])