In [1]:
%matplotlib widget

from bmcs_shear.shear_crack.crack_path import SZCrackPath
from bmcs_shear.shear_crack.stress_profile import SZStressProfile
import numpy as np
np.seterr(divide='ignore', invalid='ignore') ;

In [2]:
sz_cp = SZCrackPath(x_00=400, n_m=12)
sz_sp = SZStressProfile(sz_cp=sz_cp)
sz_cp.add_x_tip_an([400 ,100])

In [3]:
sz_sp.interact()

In [4]:
x_tip_1 = sz_cp.sz_ctr.x_tip_ak[1]
idx_tip = np.argmax( sz_cp.x_Ka[:,1] >= x_tip_1 )
u_a = sz_sp.ds.x1_Ka[idx_tip] - sz_cp.x_Ka[idx_tip]
T_ab = sz_sp.sz_cp.T_Lab[-1,:]
u_b = np.einsum('a,ab->b', u_a, T_ab)
sig_b = sz_sp.ds.sz_bd.matrix_.get_sig_a(u_b)
sig_a = np.einsum('b,ab->a', sig_b, T_ab)

In [5]:
x_tip_1, u_a, u_b, sig_b, sig_a

(array([105.]),
 array([4.25985811e-02, 9.55073263e-06]),
 array([4.25985811e-02, 9.55073263e-06]),
 array([3.00000000e+00, 5.09214521e-04]),
 array([3.00000000e+00, 5.09214521e-04]))

In [10]:
sz_sp.sig_x_tip_ak

array([3.00000000e+00, 5.09214521e-04])

In [26]:
cp = SZCrackPath(x_00=400, n_m=10)
sz_sp = SZStressProfile(sz_cp=cp)
cp.add_x_tip_an([400 ,100])
sz_sp.ds.sz_cp.sz_bd.matrix_.L_fps = 200
sz_sp.interact()

In [17]:
idx_tip = np.argmax( sz_cp.x_Ka[:,1] >= sz_cp.get_x_tip_an()[1] )
sz_sp.u_Lb[idx_tip,0]

0.04126358286958975